### ISSUE TITLE
Please provide more instructions for cache invalididation 

### ISSUE THREAD

**Issue by hulkish** [mzgoddard/hard-source-webpack-plugin#109]
Currently, I'm finding this plugin to incorrectly retain it's cache in the following scenario:

- **Errors during initial bundle**
  - This has a negative impact and actually prevents me from regularly and reliably using this plugin. 
  - Once errors occur, there seems to be no way of setting right except to `rm - rf. <cache dir>`
 - This can really put you in a state of chaos if you aren't aware - or lose sight of the fact that the cache dir exists. 

- **Additional suggestions / requests**
  - Provide more granular examples that help to prevent this. 
  - Add logging which clearly states the current cache state (for both valid and invalid)

**Comment by hulkish** [comment]
Go ahead and close this.

**Comment by mzgoddard** [comment]
Released `0.4` recently which should decrease the number of false-negatives on cached modules invalidation.

`0.4` also includes work towards logging to open up better debugging options.
