### ISSUE TITLE
What is the minimal required config?

### ISSUE THREAD

**Issue by trusktr** [mzgoddard/hard-source-webpack-plugin#112]
Before I start guessing, is it fine to have config like

```js
var HardSourceWebpackPlugin = require('hard-source-webpack-plugin');

module.exports = {
  context: // ...
  entry: // ...
  output: // ...
  plugins: [
    new HardSourceWebpackPlugin({
      cacheDirectory: 'path/to/cache/[confighash]',
      recordsPath: 'path/to/cache/[confighash]/records.json',
    }),
  ],
};
```

? Or are the hashing parts also required?

**Comment by MattSurabian** [comment]
You'd need to also define the confighash.

[This is the minimal configuration I use](https://github.com/MattSurabian/DuckHunt-JS/blob/master/webpack.config.js#L50-L56):
```
    new HardSourcePlugin({
      cacheDirectory: path.join(__dirname, 'node_modules/.cache/hardsource/[confighash]'),
      recordsPath: path.join(__dirname, 'node_modules/.cache/hardsource/[confighash]/records.json'),
      configHash: function(webpackConfig) {
        return require('node-object-hash')().hash(webpackConfig);
      }
    })
```

Note that this requires the `node-object-hash`dependency

**Comment by MattSurabian** [comment]
Worth noting that you _could_ just remove `[confighash]` from the paths of your suggested config and it would work. I like using `confighash` though because most of the time my projects end up with multiple webpack configs for different environments (dev, prod, ci, etc).

**Comment by trusktr** [comment]
Oh, okay, I do intend to use this for only one build environment. So the following would work?

```js
    new HardSourcePlugin({
      cacheDirectory: path.join(__dirname, 'node_modules/.cache/hardsource'),
      recordsPath: path.join(__dirname, 'node_modules/.cache/hardsource/records.json'),
    })
```

The assumption for my case is I have a single production build env (for now), where webpack is ran inside a system that detects file changes and invokes webpack to make incremental builds.

**Comment by MattSurabian** [comment]
Yes it should. The only thing to note is that `webpack-dev-server` makes non-obvious internal modifications to your webpack config, for example including the hot module replacement plugin. So if you're using dev server with your project you might want to consider keeping configHash in use.

**Comment by trusktr** [comment]
Thanks for the note. I'm not using dev server because there's already apache serving files for this project. What configHash and `--watch` mode?

**Comment by MattSurabian** [comment]
To my knowledge watch doesn't alter the config the way dev-server does so you should be fine.

**Comment by mzgoddard** [comment]
The minimum config in `v0.4.0` is no config! The old minimum config or the highlighted config options are also covered in the config now. https://github.com/mzgoddard/hard-source-webpack-plugin/pull/129

-----

`--watch` mode like what `webpack-dev-server` is handled by configHash. The first recommendation was to do your own configuration for separate uses. But that's a little difficult with non-obvious changes `dev-server` makes. `--watch` and other webpack command line options modify the config to the compiler instead of call methods to activate those modes. Since they modify the config `configHash` is able to record that.
