### ISSUE TITLE
Good or bad idea to check the cache into source control?

### ISSUE THREAD

**Issue by trusktr** [mzgoddard/hard-source-webpack-plugin#118]
Could checking the cache into source control mean fast builds when deploying to new machines? Or is that a bad idea?

**Comment by mzgoddard** [comment]
This is something I'd like to support but it's a long way out. The biggest issue right now is the full file paths in the different parts cache information. Iirc its not just hard-source but also the records.json part from webpack core. You could check in the cache but any new systems would have to clone to the exact file path of what was checked in. The next issue would be system idiosyncrasies will be hard to detect between different machines.

One use case that is currently supported is storing caching for Continuous Integration where those two listed problems above are very unlikely.

**Comment by MattSurabian** [comment]
Ah true, webpack resolves the absolute paths so unless your other machine had the exact directory structure stuff would break.

There's also the logistical issue of commit noise.

**Comment by trusktr** [comment]
Ah, interesting. In my case I develop in a VM that is the exact same as the
prod machines, with the exact same paths.

I put this on pause as I started randomly getting an error that I will come
back around to debug.
