### ISSUE TITLE
Support glob patterns in `environmentPaths`

### ISSUE THREAD

**Issue by trotzig** [mzgoddard/hard-source-webpack-plugin#12]
We have quite a few files that, when changed, should make the cache invalid. Right now I have to list all those files inside `environmentPaths.files`. If we could use glob patterns instead, we would be less vulnerable to stale caches when new files are added. 

Here's our current config:

```js
        files: [
          'package.json',
          'webpack.config.js',
          'webpack.config.edge.js',
          'webpack.config.production.js',
          'webpack.config.staging.js',
          'webpack.config.happo.js',
          'webpack.config.common.js',
        ],
```

With glob patterns, this would become

```js
        files: [
          'package.json',
          'webpack.config.*',
        ],
```

**Comment by mzgoddard** [comment]
I was thinking about that myself. I'll probably pop out a version with this some time today.

It's been mentioned in #7 and I tried to add some clarity in the [ReadME's cacheDirectory option info](https://github.com/mzgoddard/hard-source-webpack-plugin#cachedirectory), make sure you have a cacheDirectory in your webpack configs for each different configuration. HardSource can't determine to invalidate its cache if you build with a different config just invalidate for when the config changes.

**Comment by trotzig** [comment]
Yeah, I saw that PR. Thanks for explaining that. We start with a clean slate for production builds anyway, so the cache doesn't really come into play. I guess that means we don't actually have to list all those webpack config files though. 

Thanks for a great tool btw, it's been desperately needed by the webpack community.

**Comment by mzgoddard** [comment]
@trotzig After see-sawing for a while I figured I'm not going to implement this. There are some ways to work around instead. If your configs are in a directory just add that directory to the `environmentPaths.directories` option. The new `configHash` option can also be used to consider different webpack config changes on the file or during runtime.

**Comment by trotzig** [comment]
Okay, thanks for circling back!
