### ISSUE TITLE
Doesn't invalidate broken cache

### ISSUE THREAD

**Issue by Velenir** [mzgoddard/hard-source-webpack-plugin#148]
Great plugin. Allowed to cut my compilation time in half. I have only one problem. 

When after an seemingly innocuous but pernicious typo compilation fails with

```shell
webpack: Failed to compile
```

for whatever reason, for example a forgotten closing tag in JSX. 

Hard Source plugin caches this half - compiled file and on later attempts with already corrected code loads broken file from cache.

I have to manually delete cache for compilation to pass.

**Comment by mzgoddard** [comment]
@Velenir This is likely related to #105 which was fixed in `0.4.3`. Are you using that version or any of the patches since?

**Comment by Velenir** [comment]
I am using the latest `0.4.7` version.

Just tried to create a minimal reproducible repo with this bug and ran into a similar but not quite issue.

You can see it at [hardsource-plugin-example](https://github.com/Velenir/hardsourceplugin-example).

When I try to run in development a second time it gives me an error. That is:
1. `npm run dev`
2. After compilation finished, stop the server `Ctrl+C`
3. `npm run dev` again
4. Breaks with `TypeError: Cannot read property 'context' of undefined`

Error doesn't happen if I exclude **HardSourcePlugin** or put the component from `src/App.jsx` right into `src/index.js`. Alll of which looks very strange to me.
