### ISSUE TITLE
TypeError: this.compiler.compiler is not a function

### ISSUE THREAD

**Issue by damianobarbati** [mzgoddard/hard-source-webpack-plugin#155]
Here the repro: https://github.com/damianobarbati/react-app/tree/v1.0.3

Removing the `new HardSourcePlugin()` from the `config/webpack.config.js` works fine.

**Comment by mzgoddard** [comment]
@damianobarbati Thank you for the repo and taking the time to file this issue. That really helped so I could find the line that is broken. That line though is in webpack itself and has already been fixed. https://github.com/webpack/webpack/commit/6c0e4520ea790289187c85cbb5c49c2076d353f0 Just needs a patch release to go out containing it.

So if its an issue in webpack, what does hard-source have to do with it? hard-source has multiple reasons it needs webpack to perform an extra pass, and that needed extra pass has webpack execute the broken line. Without hard-source you're probably not using a feature or other plugin that needs webpack to do an extra pass.
