### ISSUE TITLE
Object doesn't support property or method 'e'

### ISSUE THREAD

**Issue by djeeg** [mzgoddard/hard-source-webpack-plugin#156]
Hi,

Getting this error intermittently when using HardSourceWebpackPlugin
Deleting the hard source cache directory fixes the problem
Something as small as adding an extra semi-colon can cause the issue
Thought it may have been the interplay between webpackcache+babelcache, however have disabled both and still get this error
If i run with webpackcache+babelcache without HardSourceWebpackPlugin. dont get the error
Seems to occur more often on full build rather than incremental

"hard-source-webpack-plugin": "^0.4.9",
"webpack": "^3.3.0",
"webpack-dev-middleware": "^1.11.0",
"webpack-hot-middleware": "^2.18.2",

Have tried various combinations of config

 ```
       new HardSourceWebpackPlugin({
            cacheDirectory: path.resolve(__dirname, '../../..', 'output/cache_hardsource/[confighash]'),
            //recordsPath: './output/hardsourcecache/[confighash]/records.json', //note: this is set for whole config
            configHash: require('node-object-hash')({sort: false}).hash,
            // configHash: function(webpackConfig) {
            //     return process.env.APP_ENV; //tocheck: things like dev-server make unseen modifications to your config, which should be cached independently
            // },
            // environmentHash: { //removed as only need this for vendoring or yarn, https://bocoup.com/blog/screencast-transcript-improving-webpack-build-times
            //     root: process.cwd(),
            //     directories: ['node_modules'],
            //     files: ['package.json'],
            // },
        })
```

**Comment by mzgoddard** [comment]
Hey @djeeg, it'd help me if you can give me some more info.

Can you post the relevant error stack trace? Is it a build time or runtime error?

What other plugins and loaders are you using when this happens?

**Comment by mzgoddard** [comment]
Closing due to lack of info.
