### ISSUE TITLE
Compilation archetype is never thawed

### ISSUE THREAD

**Issue by bazyli-brzoska** [mzgoddard/hard-source-webpack-plugin#157]
Fantastic job on the pluginification, @mzgoddard!

We're trying to freeze and thaw custom properties of webpack `dependencies` and `compilation` that we use in our i18n plugin. The code is super simple, and thawing dependencies works, however the `--hard-source-after-thaw-compilation` hook is **never called**.

We want to save extra properties from the `compilation` object, put there by our i18n plugin. The code is super simple:

```js
  compiler.plugin('--hard-source-after-freeze-compilation', function i18nFreeze(frozen, compilation, extra) {
    if (compilation.messagesPerFile) {
      if (!frozen) {
        frozen = {}
      }
      frozen.messagesPerFile = compilation.messagesPerFile
      frozen.differencesPerFile = compilation.differencesPerFile
    }

    return frozen
  })
  compiler.plugin('--hard-source-after-thaw-compilation', function i18nThaw(compilation, frozen, extra) {
    // never gets executed!
    if (compilation && frozen && frozen.messagesPerFile) {
      compilation.messagesPerFile = frozen.messagesPerFile
      compilation.differencesPerFile = frozen.differencesPerFile
    }

    return compilation
  })
```

**Comment by mzgoddard** [comment]
Pruning old issues.

For future readers of this issue: Webpack's `compilation` is antithetical to thawing. Instead the standard webpack process "thaws" the compilation. If you need to attach additional information to webpack's compilation that you want to "thaw" do so during one of webpack's normal compilation hooks like compiler's `compilation` hook or compilation's `seal` hook. There isn't a general hook to use to thaw your data correctly. It will depend on your use case.
