### ISSUE TITLE
TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by LenaNesg** [mzgoddard/hard-source-webpack-plugin#160]
My package.json:
{
  "name": "leverate-socialacr-webapp",
  "version": "1.0.0",
  "description": "SocialACR Web Application",
  "main": "index.js",
  "scripts": {
    "prestart": "babel-node tools/startMessage.js",
    "start": "npm-run-all --parallel open:src lint:watch",
    "open:src": "babel-node tools/srcServer.js",
    "lint": "node_modules/.bin/esw webpack.config.* src tools",
    "lint:watch": "npm run lint -- --watch",
    "onesky": "babel-node tools/oneSkyImport.js",
    "framework": "npm install activ8-client-framework",
    "test": "mocha --reporter spec tools/testSetup.js \"src/**/*.test.js\"",
    "test:watch": "npm run test -- --watch",
    "clean-dist": "npm run remove-dist && mkdir dist",
    "remove-dist": "node_modules/.bin/rimraf ./dist",
    "build:html": "babel-node tools/buildHtml.js",
    "prebuild": "npm-run-all clean-dist framework onesky build:html",
    "build": "babel-node tools/build.js",
    "postbuild": "babel-node tools/distServer.js",
    "webpack:dev": "webpack  --config webpack.config.prod-dev.js",
    "build:prod-dev": "npm-run-all framework onesky build:html webpack:dev",
    "build:prod-dev-l": "npm-run-all build:html webpack:dev",
    "clean:hot-update": "rimraf ../Leverate.SocialACR.Broker.IIS/Manage/*.hot-update.js ../Leverate.SocialACR.Broker.IIS/Manage/*.hot-update.json ../Leverate.SocialACR.Broker.IIS/*.hot-update.js ../Leverate.SocialACR.Broker.IIS/*.hot-update.json"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/yuvalkalev/SocialACR.git"
  },
  "author": "Yuval Kalev",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/yuvalkalev/SocialACR/issues"
  },
  "homepage": "https://github.com/yuvalkalev/SocialACR#readme",
  "dependencies": {
    "activ8-client-framework": "^2.1.16",
    "babel-plugin-es6-promise": "^1.0.0",
    "babel-plugin-transform-object-assign": "^6.22.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-runtime": "^6.23.0",
    "bootstrap": "3.3.6",
    "chart.js": "^2.3.0",
    "cheerio": "^0.20.0",
    "create-react-class": "^15.5.3",
    "d3": "^4.6.0",
    "d3-scale": "^1.0.4",
    "es6-promise-polyfill": "^1.2.0",
    "eventsource-polyfill": "^0.9.6",
    "hard-source-webpack-plugin": "^0.4.9",
    "i18next": "^4.1.1",
    "i18next-xhr-backend": "^1.2.1",
    "img-loader": "^1.3.1",
    "immutable": "^3.8.1",
    "jquery": "2.2.3",
    "jszip": "^3.1.3",
    "mixpanel-browser": "^2.9.17",
    "moment": "^2.18.1",
    "ms-signalr-client": "^2.2.5",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-cookie": "^1.0.3",
    "react-day-picker": "^2.4.1",
    "react-dom": "15.4.0",
    "react-dropzone": "^3.7.3",
    "react-i18next": "^1.11.0",
    "react-mixpanel": "0.0.8",
    "react-redux": "^5.0.5",
    "react-router": "^2.8.1",
    "react-router-redux": "^4.0.4",
    "react-slick": "^0.14.11",
    "react-sortable-hoc": "^0.6.3",
    "react-stockcharts": "^0.6.1",
    "react-toggle-switch": "^2.1.3",
    "react-tooltip": "^3.1.8",
    "react-virtualized": "^9.7.5",
    "recharts": "^1.0.0-alpha.2",
    "redux": "^3.7.1",
    "redux-devtools-extension": "^1.0.0",
    "redux-thunk": "2.0.1",
    "slick-carousel": "^1.6.0",
    "superagent": "^3.1.0",
    "toastr": "^2.1.2"
  },
  "devDependencies": {
    "babel-cli": "^6.8.0",
    "babel-core": "6.8.0",
    "babel-loader": "^7.1.1",
    "babel-plugin-react-display-name": "2.0.0",
    "babel-plugin-transform-object-assign": "^6.22.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-register": "6.8.0",
    "bundle-loader": "^0.5.4",
    "chart.js": "^2.5.0",
    "cheerio": "^0.20.0",
    "clean-webpack-plugin": "^0.1.16",
    "colors": "1.1.2",
    "compression": "1.6.1",
    "compression-webpack-plugin": "^0.4.0",
    "copy-webpack-plugin": "^3.0.1",
    "cross-env": "1.0.7",
    "css-loader": "^0.28.4",
    "enzyme": "2.2.0",
    "es6-promise": "^4.1.0",
    "es6-promise-polyfill": "^1.2.0",
    "eslint": "2.9.0",
    "eslint-plugin-import": "1.6.1",
    "eslint-plugin-react": "5.0.1",
    "eslint-watch": "2.1.11",
    "eventsource-polyfill": "0.9.6",
    "expect": "1.19.0",
    "expose-loader": "^0.7.1",
    "express": "4.13.4",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "0.8.5",
    "jsdom": "8.5.0",
    "json-loader": "^0.5.4",
    "mocha": "2.4.5",
    "nock": "8.0.0",
    "node-sass": "^4.5.3",
    "npm-run-all": "1.8.0",
    "onesky-utils": "^1.1.0",
    "open": "0.0.5",
    "react-addons-test-utils": "15.0.2",
    "redux-immutable-state-invariant": "1.2.3",
    "redux-mock-store": "1.0.2",
    "rimraf": "2.5.2",
    "sass-loader": "^4.1.1",
    "style-loader": "0.13.1",
    "url-loader": "0.5.7",
    "webpack": "^3.2.0",
    "webpack-clean-obsolete-chunks": "^0.2.0",
    "webpack-dev-middleware": "1.6.1",
    "webpack-hot-middleware": "2.10.0"
  }
}
My webpack.config.prod-dev:
const webpack = require('webpack');
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HardSourceWebpackPlugin = require('hard-source-webpack-plugin');
const CleanObsoleteChunks = require('webpack-clean-obsolete-chunks');
const CleanWebpackPlugin = require('clean-webpack-plugin'); //installed via npm
const distFolder = __dirname + '/../Leverate.SocialACR.Broker.IIS/';
// the path(s) that should be cleaned
let pathsToClean = [
  '*.hot-update.json', 
  '*.hot-update.js', 
]

// the clean options to use
let cleanOptions = {
  root:     distFolder,  
  verbose:  true,
  dry:      false
}
module.exports = {
    devtool: 'inline-eval-cheap-source-map',
    entry: [
        'babel-polyfill', // necessary for hot reloading with IE 
        './src/index'
    ],
    watch: true,
    cache: false,
    target: 'web',
    output: {
        path: distFolder,
        publicPath: '/',
        sourceMapFilename: "bundle.js.map",
        filename: 'bundle.js'
    },
    devServer: {  // http://webpack.github.io/docs/webpack-dev-server.html#hot-mode
        noInfo: true, // only errors & warns on hot reload
        hot: true,
        overlay:true,//display errors
        contentBase: './src', // boolean | string | array, static file location
        overlay:true,//display errors
        watchOptions: {
            aggregateTimeout: 100,
            poll: 500,
        }, 
    },
    plugins: [ 
        new HardSourceWebpackPlugin({
            cacheDirectory: 'node_modules/.cache/hard-source/[confighash]',
            recordsPath: 'node_modules/.cache/hard-source/[confighash]/records.json',
            configHash: require('node-object-hash')({ sort: false }).hash
        }), 
        new webpack.HotModuleReplacementPlugin(),
        new webpack.DefinePlugin({
            __DEVCLIENT__: true,
            __DEVSERVER__: false
        }),
        new CopyWebpackPlugin([{ from: './src/media', to: distFolder + '/media' }]),
        new CopyWebpackPlugin([{ from: './locales', to: distFolder + '/locales' }]),
        new ExtractTextPlugin('styles.css'),
        new webpack.ProvidePlugin({ jQuery: 'jquery', $: 'jquery', jquery: 'jquery', Promise: 'es6-promise' }),
        new CleanWebpackPlugin(pathsToClean, cleanOptions),          
    ],
    node: {
        fs: "empty"
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                include: path.join(__dirname, 'src'),
                use: [
                    {
                        loader: "babel-loader",
                        options: {
                            cacheDirectory: false
                        }
                    },
                ],
            },
            {
                test: require.resolve("jquery"),
                use: [
                    { loader: "expose-loader", options: 'jQuery' },
                    { loader: "expose-loader", options: '$' },
                ]

            },
            { test: /\.(jpe?g|png|gif|svg|xls|xlsx|csv)$/i, loader: 'file-loader' },
            {
                test: /\.scss$/,
                //loader: ExtractTextPlugin.extract("style", "css!sass")
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    //resolve-url-loader may be chained before sass-loader if necessary
                    use: ['css-loader', 'sass-loader']
                })
            },
            {
                test: /(\.css)$/,
                //loader: ExtractTextPlugin.extract("css?sourceMap")
                use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: "css-loader"
                }),
                // include: [path.join(__dirname, '..', 'node_modules')],
            },
            {
                test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
                use: [{ loader: 'file-loader' }]

            },
            {
                test: /\.(woff|woff2)$/,
                use: [{ loader: 'url-loader', options: "prefix=font/&limit=5000" }]

            },
            {
                test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
                use: [
                    {
                        loader: 'url-loader',
                        options: "limit=10000&mimetype=application/octet-stream"
                    }]
            },
            {
                test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
                use:
                [{
                    loader: 'url-loader',
                    options: "limit=10000&mimetype=image/svg+xml"
                }]
            },
            { // for third-party minified scripts, don't process require()
                test: /\.min\.js$/,
                include: /(node_modules|bower_components)/,
                loader: 'script-loader'
            }
        ]
    }
};

On running npm run build:prod-dev or npm run build:prod-dev-l I have following error 
Unhandled rejection TypeError: Cannot read property 'reduce' of undefined
    at C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\hard-source-webpack-plugin\index.js:1042:17
    at addPromise (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\hard-source-webpack-plugin\index.js:1008:21)
    at Array.forEach (native)
    at walkDependencyBlock (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\hard-source-webpack-plugin\index.js:1014:30)
    at getModuleCacheItem (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\hard-source-webpack-plugin\index.js:1025:9)
    at C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\hard-source-webpack-plugin\index.js:1433:19
    at fromCache (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\hard-source-webpack-plugin\index.js:1411:18)
    at C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\hard-source-webpack-plugin\index.js:1418:18
    at C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\hard-source-webpack-plugin\index.js:1427:12
    at C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\lib\NormalModuleFactory.js:64:5
    at applyPluginsAsyncWaterfall (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\lib\NormalModuleFactory.js:246:4)
    at C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\tapable\lib\Tapable.js:250:11
    at NormalModuleFactory.<anonymous> (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\hard-source-webpack-plugin\index.js:1532:14)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\tapable\lib\Tapable.js:254:13)
    at NormalModuleFactory.create (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\lib\NormalModuleFactory.js:230:8)
    at iteratorFactory (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\lib\Compilation.js:233:12)
    at C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\node_modules\async\dist\async.js:3083:16
    at eachOfArrayLike (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\node_modules\async\dist\async.js:1003:9)
    at eachOf (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\node_modules\async\dist\async.js:1051:5)
    at Object.eachLimit (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\node_modules\async\dist\async.js:3145:5)
    at Compilation.addModuleDependencies (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\lib\Compilation.js:214:12)
    at Compilation.processModuleDependencies (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\lib\Compilation.js:199:8)
    at Compilation.moduleReady (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\lib\Compilation.js:447:10)
    at buildModule (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\lib\Compilation.js:443:17)
    at building.forEach.cb (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\lib\Compilation.js:144:27)
    at Array.forEach (native)
    at callback (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\lib\Compilation.js:144:13)
    at module.build (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\lib\Compilation.js:171:11)
    at MultiModule.build (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\lib\MultiModule.js:36:10)
    at Compilation.buildModule (C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\node_modules\webpack\lib\Compilation.js:146:10)

Sometimes if I change the place of  new HardSourceWebpackPlugin into array of plugins it start to working Please help me

**Comment by ettavolt** [comment]
There is a problem ``getModuleCacheItem``. At the begging it deserializes item in ``moduleCache``, but later in ``walkDependencyBlock`` it may encounter a ``depCacheItem`` that wasn't yet deserialized.

**Comment by LenaNesg** [comment]
I resolve this problem by removing folder .cache ☺
Thanks and best regards ☺

Elena Nesgovorov
Senior Software Developer
Ext.

**Comment by ettavolt** [comment]
Well, in this case you can simply remove the plugin from your webpack configuration. You'll get same effect.

**Comment by mzgoddard** [comment]
Fixed through a manual merge of @ettavolt's change.
