### ISSUE TITLE
Can't resolve 'fs'

### ISSUE THREAD

**Issue by elijah-schow** [mzgoddard/hard-source-webpack-plugin#161]
I just added the hard source plugin to my webpack config. Once webpack builds the application and fires up the dev server, I get this error:

```
./~/hard-source-webpack-plugin/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/elijahschow/Repositories/frontend/node_modules/hard-source-webpack-plugin'
 @ ./~/hard-source-webpack-plugin/index.js 2:9-22
 @ multi (webpack)-dev-server/client?http://localhost:8080 angular angular-cache angular-route angular-sanitize angular-ui-bootstrap babel-polyfill decimal.js elastic.js hard-source-webpack-plugin highcharts jquery js-cookie json-cycle linq moment ngUpload promise-polyfill snapsvg-cjs textangular universal-ga whatwg-fetch
```

**Comment by sergeyzenchenko** [comment]
Same for me. Any idea how to solve it?

**Comment by adhityan** [comment]
Same for me.

**Comment by AverageZ** [comment]
This seems to have solved it for me: https://github.com/webpack-contrib/css-loader/issues/447#issuecomment-285603267

**Comment by mzgoddard** [comment]
@AverageZ Good catch. I think that explains the issue well too. `hard-source` doesn't add any code to your modules. This error is from modules that depend on `fs` or loaders that have added a dependency to `fs` without the webpack `node: {fs: 'empty'}` workaround or `target: 'node'`. In @elijah-schow's case, some module built by webpack depended on `hard-source-webpack-plugin`, trying to build the plugin into the output asset.
