### ISSUE TITLE
How does this work with multiple processes?

### ISSUE THREAD

**Issue by tarjei** [mzgoddard/hard-source-webpack-plugin#165]
Hi, 

I usually run webpack with webpack-dev-server in one process and karma watching my tests in another process. How does `hard-source-webpack-plugin` handle that situation? Should I use separate directories?

**Comment by bazyli-brzoska** [comment]
Correct, you need to use separate cache directories.

**Comment by tarjei** [comment]
Thanks @bazyli-brzoska
