### ISSUE TITLE
react-hot-loader causes hard-source to fail on second compilation

### ISSUE THREAD

**Issue by jbarranis** [mzgoddard/hard-source-webpack-plugin#192]
This plugin is great! It sped up my build by a lot. Unfortunately, it isn't working for my app at the moment. I'm getting a bunch of warnings for every file that's importing a path that's using an alias. e.g.:

In webpack config:
```
// stuff
resolve: {
  // stuff
  alias: {
    utility: path.resolve(__dirname, '../app/shared/utility/)
  }
}
```

In ./app/components/SomeComponent.js:
```
import { someFunction } from 'utility/helpers.js';
```

When starting the app, this warning would appear (and the page that imports the function breaks):
```
WARNING in ./app/components/SomeComponent.js
9:86-106 "export 'someFunction' was not found in 'utility/helpers.js'
  @ ./app/components/SomeComponent.js
  @ ./app/routes/index.js
  @ ./app/app.js
  @ multi (wepack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill react-hot-loader/patch webpack-dev-server/client?http://0.0.0.0:8080 webpack/hot/only-dev-server ./app/app.js
```

Any ideas is appreciated!

**Comment by jasononeil** [comment]
We're having the same problem. I've tracked this down as being a conflict between react-hot-loader and hard-source-webpack-plugin.

Here's a repo with a reproducible example: https://github.com/jasononeil/react-hot-loader-hard-source-webpack-plugin-problem/commits/master

Steps to reproduce:

1. [Start with create-react-app](https://github.com/jasononeil/react-hot-loader-hard-source-webpack-plugin-problem/commit/70af0b8419b57070531e9a9b9182602622f90d45)
2. [Eject!](https://github.com/jasononeil/react-hot-loader-hard-source-webpack-plugin-problem/commit/60dd4d6d8de86ab7b3e679d9964c3847b221d4f0)
3. [Add react-hot-loader](https://github.com/jasononeil/react-hot-loader-hard-source-webpack-plugin-problem/commit/ee43c404ed8598cd1f275de044efb83310dfc169)
4. [Add hard-source](https://github.com/jasononeil/react-hot-loader-hard-source-webpack-plugin-problem/commit/480c1532af2f3e1395cca08e5268993da1b1f115)

and then....

5. `yarn start`. Webpack fires up, edit some files, hot reloading is working.
6. Kill webpack, run `yarn start` again - and you'll get all of the warnings `export 'default' not found in '....'`

I suggest changing the issue title to "react-hot-loader causes hard-source to fail on second compilation" or similar.

I'm happy to have a go at fixing this issue but would appreciate if one of the maintainers can point me in the right direction (if they have a hunch as to where I should look to solve the problem)

**Comment by jbarranis** [comment]
@jasononeil Thanks for finding the cause! Yep, if I disable react-hot-loader in my app, it works. I changed the issue title per your suggestion.

**Comment by fuchao2012** [comment]
Also, find this warning in ng4+

```
...
WARNING in ./src/main/webapp/app/workflow/detail/book/detail-suggest.component.ts
46:41-56 "export 'WorkFlowService' was not found in '../../workflow.service'
 @ ./src/main/webapp/app/workflow/detail/book/detail-suggest.component.ts
 @ ./src/main/webapp/app/workflow/workflow.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/bootstrap.ts
 @ multi ./src/main/webapp/bootstrap.ts webpack-hot-middleware/client?&reload=true
...
```

tons of warning logs

**Comment by noe132** [comment]
also using with vue-loader
```
WARNING in ./src/app/main.js
11:0-3 "export 'default' (imported as 'Vue') was not found in 'vue'
 @ ./src/app/main.js

WARNING in ./src/app/main.js
14:4-7 "export 'default' (imported as 'Vue') was not found in 'vue'
 @ ./src/app/main.js

WARNING in ./src/app/main.js
18:16-19 "export 'default' (imported as 'App') was not found in './App'
 @ ./src/app/main.js

WARNING in ./src/app/App.vue
20:2-16 "export 'default' (imported as '__vue_script__') was not found in '!!babel-loader!../../node_modules/vue-loader/lib/selector?type=script&index=0&bustCache!./App.vue'
 @ ./src/app/App.vue
 @ ./src/app/main.js

WARNING in ./src/app/routes.js
6:0-3 "export 'default' (imported as 'Vue') was not found in 'vue'
 @ ./src/app/routes.js
 @ ./src/app/main.js
```

**Comment by gknapp** [comment]
Seeing similar issues, first in the dev build where we're using HMR. Switched this over to our production config where HMR is not used - same issues. No build speed up either strangely, excerpt:

```
WARNING in ./node_modules/proj4/lib/transform.js
9:81-91 "export 'PJD_7PARAM' was not found in './constants/values'
 @ ./node_modules/proj4/lib/transform.js
 @ ./node_modules/proj4/lib/index.js
 @ ./app/ol-proj-setup.js
 @ ./app/index.jsx
 @ multi ./app/index.jsx
```

Using webpack 3.8.1.

Does plugin order matter?

Plugins in use:

```javascript
  plugins: [
    new CleanWebpackPlugin(['build']),
    HtmlWebpackPluginConfig,
    CopyWebpackPluginConfig,
    new webpack.IgnorePlugin(/redux-logger/),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production')
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      parallel: true
    }),
    new HardSourceWebpackPlugin()
  ]
```

**Comment by YiSiWang** [comment]
I seems to be related to *ES Module*.

```js
// webpack.config.js
const HardSourceWebpackPlugin = require('hard-source-webpack-plugin')
module.exports = {
  entry: './index.js',
  output: {
    filename: 'out.js',
  },
  plugins: [
    new HardSourceWebpackPlugin(),
  ],
}

// index.js
import esm from './test.esm.js'
import common from './test.common.js'
console.log(esm)
console.log(common)

// test.esm.js
export default 'es module'

// test.common.js
module.exports = 'commonjs'
```

WARNING: `"export 'default' (imported as 'esm') was not found in './test.esm.js'`
If you comment out the ES Module, it works.

Repo: https://github.com/YiSiWang/hard-source-demo

**Comment by YiSiWang** [comment]
Adding [transform-es2015-modules-commonjs](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) might temporarily solve the problem.

**Comment by junbinku** [comment]
Same happened showing tons of warning on the second compile. First compile successfully webpacked. Version 0.4.11 on reactjs

**Comment by sqpdln** [comment]
did anyone manage to solve this? having the same issue with vue and webpack-dev-middleware. tried the commonjs approach but it didn't work.

**Comment by mzgoddard** [comment]
@jbarranis I just released `0.5` (after it being in beta since summer), let me know if it solves this for you. From my experience `0.5` fixes this issue. The fix was one that would be too hard to back port to `0.4`.

**Comment by kkkrist** [comment]
Yay! 0.5 fixes it for me! Thank you!!

**Comment by jbarranis** [comment]
@mzgoddard That fixed it! Thanks!!
