### ISSUE TITLE
Tons of warnings on the first compilation

### ISSUE THREAD

**Issue by 5angel** [mzgoddard/hard-source-webpack-plugin#195]
The plugin works, but on the first compilation it emits hundreds of warning messages, they all look like that:
```
WARNING in ./node_modules/lodash-es/_baseGetTag.js
10:30-36 "export 'default' (imported as 'Symbol') was not found in './_Symbol.js'
 @ ./node_modules/lodash-es/_baseGetTag.js
 @ ./node_modules/lodash-es/isPlainObject.js
 @ ./node_modules/redux/es/createStore.js
 @ ./node_modules/redux/es/index.js
 @ ./src/modules/main/store.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 webpack/hot/dev-server ./src/index.js
```
Is this the default behavior?

**Comment by cristianmartinez** [comment]
Any news?

**Comment by 5angel** [comment]
@cristianmartinez nope, there were critical issues with this plugin, so we removed it altogether. I don't see much activity in the repo, so I guess this is a miss. Too bad, the plugin seemed promising. I still hope someone picks this up.

**Comment by OlzhasAlexandrov** [comment]
Had the same with a basic webpack setup for pug sketching with [google material components](https://github.com/material-components/material-components-web).

On the second webpack build, it produced multiple warnings for GMC.

**Comment by mzgoddard** [comment]
@5angel Do you get this issue in the `beta` version? I can only repro in `0.4`

**Comment by mzgoddard** [comment]
The "`beta`" is now the latest at `0.5`.

**Comment by mzgoddard** [comment]
Pretty sure this is the `importedVar` member that was missing in some of the harmony support in `0.4`. `0.5` adds that member for the remaining harmony dependencies.
