### ISSUE TITLE
Non-valid stats.json 

### ISSUE THREAD

**Issue by DostalTomas** [mzgoddard/hard-source-webpack-plugin#199]
If webpack is executed with `--profile --json > stats.json` options, some invalid string is prepended into file.

```
[hard-source:core] HardSourceWebpackPlugin is writing to a new confighash path for the first time: /.../src/main/resources/resources/node_modules/.cache/hard-source/38fe133c399b01985aff65e0e14c2a441047e6cc866b3dff9d90a1f0031dca7f
{
  "errors": [],
  "warnings": [],
  "version": "3.8.1",
  "hash": "a7f5f5e4b6d74de1a071",
  "time": 16759,
.......
```

**Comment by mzgoddard** [comment]
@DostalTomas Thanks for opening this issue. I'll change the future behaviour to have hard-source's logging use `stderr` in the future.

A workaround if it helps you can write a small plugin for webpack to take control of `hard-source`'s logging.

https://github.com/mzgoddard/hard-source-webpack-plugin/blob/b7c5888699fff5cd5ac258f0809bd58f7354b145/lib/logger-factory.js#L22-L29

```js
compiler.plugin('hard-source-log', function(message) {
  console[message.level].call(
    console,
    'hard-source:' + message.from, message.message
  );
});
```
