### ISSUE TITLE
It is not considering changes made in webpack config file after the first build

### ISSUE THREAD

**Issue by Narik44** [mzgoddard/hard-source-webpack-plugin#204]
I am using a constant (__CLIENT__) in define plugin of my webpack config.If i build my webpack file with __CLIENT__ = true during my first build and then if i change __CLIENT__ =false during my second build,it is still considering it as __CLIENT__= true .Is there a way  to get around this

**Comment by mzgoddard** [comment]
@Narik44 You can build and assign a custom [`configHash`](https://github.com/mzgoddard/hard-source-webpack-plugin#confighash). The default is the `node-object-hash` npm module. In many cases that is enough. For cases like yours you can build a from scratch value, or depend on `node-object-hash` yourself and use it plus some extra logic yourself.
