### ISSUE TITLE
Karma related issue

### ISSUE THREAD

**Issue by 1ka** [mzgoddard/hard-source-webpack-plugin#206]
When running a build under Karma, it fails on the second build with a message like:

> reduce is not a function of undefined

This is in the index.js file at line 1050.

If we change line 1048 to extend the check to this:

`
depCacheItem && depCacheItem.fileDependencies &&
`

then the Karma build passes. 

This only affects our Karma test build, the main dev builds are fine. I'm not sure what Karma is doing under the covers to cause this, but caching with Karma does seem to work with this minor change.

Happy to give more information if I can, but I might not be able to isolate this into a simple test. Also happy to do a pull request if that's easier too (just that I need to set up the environment to enable me to do this and it might be easier if you guys already have that for such a simple fix :-) )

**Comment by 1ka** [comment]
Might also be related to issue 160

https://github.com/mzgoddard/hard-source-webpack-plugin/issues/160

**Comment by mzgoddard** [comment]
Thanks for opening this issue @1ka. Looks like this was an area that was missing the following that similarly appears in some other areas.

```diff
--- index.js (saved version)
+++ (current document)
@@ -1035,6 +1035,10 @@
             ) {
               var depIdentifier = identifierPrefix + resolveItem.request;
               var depCacheItem = moduleCache[depIdentifier];
+              if (typeof depCacheItem === 'string') {
+                depCacheItem = JSON.parse(depCacheItem);
+                moduleCache[depIdentifier] = depCacheItem;
+              }
               if (
                 depCacheItem &&
                 depCacheItem.fileDependencies
```

But I'll fix this with #169 for now.

**Comment by mzgoddard** [comment]
The change is in `0.4.15` and `0.5.0-rc.7`

**Comment by 1ka** [comment]
I'll try it on Tuesday when I'm back at work and let you know the results. Thanks  :-)

**Comment by 1ka** [comment]
Cool, that all worked in 0.5.0, 0.5.1 - Thanks
