### ISSUE TITLE
typescript webpack.config.ts file

### ISSUE THREAD

**Issue by mikehaas763** [mzgoddard/hard-source-webpack-plugin#208]
To work out of the box with typescript (via a webpack.config.ts file), it'd be *awesome* if this project used something like https://github.com/Microsoft/dts-gen as a part of the build/release process.

**Comment by mzgoddard** [comment]
@mikehaas763 I'm not sure how to run that tool. The documentation makes me think its used by downstream users in their projects. Or rather I'm not sure how to make it part of my publishing process without going some weird loophole like using a git url to globally install hard-source so dts-gen can find it.

**Comment by mikehaas763** [comment]
oh, I honestly didn't know that the tool had those constraints. Are you open to a PR that adds handwritten typescript type definitions to this project? It just makes it a lot easier for downstream consumers (like me) who use typescript

**Comment by mzgoddard** [comment]
@mikehaas763 totally. I'd be happy to include that. It seems like a regular npm package norm to me by now.

**Comment by astorije** [comment]
@mikehaas763, are you still considering opening a PR for it? That would be terrific! 🙏 Thanks in advance!

**Comment by woitechen** [comment]
I added a PR on DefinitelyTyped. [Link](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26972).
