### ISSUE TITLE
compilation.compiler.context is undefined at hard-compilation-plugin.js#L33

### ISSUE THREAD

**Issue by piecyk** [mzgoddard/hard-source-webpack-plugin#230]
Hello, 

was playing around with new released 0.5.9 👏 💪 
made an typo in stylus file that produce syntax error that was not correctly handled... 

`compilation.compiler.context` was undefined at 
https://github.com/mzgoddard/hard-source-webpack-plugin/blob/master/lib/hard-compilation-plugin.js#L33

then `RequestShortener` will just fail... also `compilation.compiler.name` is `extract-text-webpack-plugin`

dependencies   
`webpack: 3.10.0`
`hard-source-webpack-plugin: 0.5.9`

Another problem that i'm trying to pin with webpack3 is that module errors are not cached? handled correctly... hard to say ( current trying to write an test ( or firstly understand how tests works :) to catch that behaviour )  

Basic run webpack in watch, made some changes that produce webpack compilation to fail, 
kill it, run again, no errors are reported... warnings are preserved

Will create an issue when i will have more knowledge about it 👍

**Comment by mzgoddard** [comment]
@piecyk Thanks for opening the issue. Published a fix in `0.5.10`.

ModuleError objects in `module.errors` are frozen. Though I'm wondering if that should be bothered with. Webpack's memory cache skips errored modules, and opts to rebuild until a module doesn't error. That should currently be honored. I'm thinking it could be a non-module error. Like one posted on the compilation? Hmm.

**Comment by mzgoddard** [comment]
Please do open an issue for that if you can find a reproduction.

**Comment by piecyk** [comment]
@mzgoddard 👍
