### ISSUE TITLE
Doesn't appear to be working with spike

### ISSUE THREAD

**Issue by jescalan** [mzgoddard/hard-source-webpack-plugin#24]
Hey there,

So I know you might not really care about this, but figured I'd at least post it here in case you might see a quick solution or have the interest to walk me through a way to dive deeper. I am more than happy to get my hands dirty, but would need a little hand-holding at the beginning as I'm not nearly as familiar with webpack's internals or cache structure as you are.

I work on [spike](https://github.com/static-dev/spike), which is essentially a static website generator that uses webpack as its core compiler. So we route not only js, but also html and css through webpack's compiler, and have a plugin to inject and extract files from the pipeline so it behaves as expected. This tool is still in pre-release and hasn't seen any publicity yet, but we are gearing up to make a publicity push sometime in the next couple of months and are expecting decent adoption.

Especially for static sites, something like this plugin would be a game-changer. If we could get this working, someone would be able to build out even very large and content-heavy sites as completely static. So you could take, say, a wordpress site with a couple thousand posts, add the wordpress api plugin, hook up the API to spike, and have it generate the site static. Then take a webhook from wordpress and link it up to your host to have it rebuild when a new post goes up.

At the moment, having a persistent cache between builds is the only thing that stands in the way of making this tool able to easily and quickly handle any size/complexity of website, so needless to say we are really excited to try to get it integrated.

So on to the actual issue! I hooked up the plugin and ran it with a test site in which I generated a couple hundred view files with some resource-heavy transforms. Initial compile was ~30s, and subsequent compiles averaged out around ~24s. I'm not sure how much reduction I should expect, but presumably it would be a little more than this?

I peeked into the `records.json` and `cache/resolve.json` files to ensure that all the files were being tracked, as spike does do a little extra manipulation with webpack's pipeline outside the ordinary, but it does appear as if they are all on there. [Here's a sample project that demonstrates the issue](https://github.com/jescalan/spike-hard-source-test). You can run a compile using `npm start` if you are testing.

Thanks so much for working on this incredible plugin, and for taking the time to read this little novel I've written! 💖

**Comment by kylemac** [comment]
FYI: for help with @jescalan's test project, spike's configuration (and therefore the configuration of `hard-source-webpack-plugin` is handled in the `./app.js`

[link with line reference](https://github.com/jescalan/spike-hard-source-test/blob/master/app.js#L27)

**Comment by mzgoddard** [comment]
@jescalan @kylemac thanks for pitching in with and on this issue. I should have some time to look at your sample project for spike soon to see if I can figure why the difference is ... less than I'd expect to.

I'm definitely interested in spike's use case. One of my test projects for changes to HardSource is a personal static site generator for a blog I made in May that in a way led to HardSource's existence.

**Comment by mzgoddard** [comment]
@jescalan I gave your test repo a run. Thanks for setting up that test repo.

Looks like spike's plugins use `userRequest` on the module and HardSource is serializing that but not standing it back up. I'll make that change. (Makes me wonder how it was running for you.) I had to add `readme.md` and `records.json` to the ignore list. They were being picked up and semi built but into modules with a `_src` that was undefined, causing an error.

After I got the test repo building reliably I ended with a different time result. My first build takes about 27 seconds and later builds 7 or 8 seconds. I dropped in a [little plugin](https://gist.github.com/mzgoddard/917207ea6444c04eaf62f9907f891a2a) I use to pull out some high level time info from webpack and noticed both build times have a fixed 7 second activity that is is outside of webpack. So really that test repo on my system went from a 20 second build to half second plus the 7 seconds of non-webpack work. I'm not sure what explains the times you're seeing.

**Comment by kylemac** [comment]
@mzgoddard couple questions: would you be able share the alterations you made to the test project? and was there any logic updates to `hard-source-webpack-plugin`, and if so are they in the most recent version or maybe on a branch? 

also, thanks for digging into this with us. the idea of having incremental builds for our SSG is really exciting. 

🚣

**Comment by jescalan** [comment]
Just an update, we did get this working and are now seeing compiles times under 1s after the first compile. This is amazing! Thank you **so** much for your incredible work on this plugin. It's really going to be a game changer for us.

**Comment by mzgoddard** [comment]
@kylemac I made these changes. https://github.com/mzgoddard/spike-hard-source-test/commit/68dd21a619dfd180d290b5b707ef5ae006da0dc8 A change was needed in hard-source as well, thats in version `0.0.36`.

@jescalan I am super glad its working for you all. :smile:

**Comment by kylemac** [comment]
thanks @mzgoddard! as jeff said, we got it working and are pretty excited over here. we're working on getting it to work properly on our deployment/static-host of choice ([netlify](netlify.com)). right now their cache directory doesn't pass your `envHash` mtime test, but seems like a solvable issue. incremental builds, here we come!

**Comment by mzgoddard** [comment]
Going to close this since it's working for you all now. For your envhash times in netlify you could disable envhash with `environmentPaths: false,` and include a hashed version of the file content of package.json through the new `configHash` option.

**Comment by jescalan** [comment]
@mzgoddard awesome, thank you!

**Comment by mzgoddard** [comment]
@jescalan eh I should mention that using my last advice means if you bump versions of deps but the package.json doesn't reflect that you'll get cached copies of modules instead of any newly installed modules. You'll need to dump the cache manually (delete its folder) in that case, since thats the check `environmentPaths` does for you. In this case you should get working builds assuming any deps matching expected to work semver ranges. But you will not automatically have the absolute latest without building in more of what environmentPaths does into configHash.
