### ISSUE TITLE
Error - TypeError: Cannot read property 'sourcesContent' of undefined

### ISSUE THREAD

**Issue by MrFrankel** [mzgoddard/hard-source-webpack-plugin#241]
i'm getting this error running all version since 0.5.8

Error: Child compilation failed:
  Cannot read property 'sourcesContent' of undefined:
  TypeError: Cannot read property 'sourcesContent' of undefined
  
  - compiler.js:76 
    [webapp]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:300 compile
    [webapp]/[webpack]/lib/Compiler.js:300:11
  
  - Compiler.js:510 applyPluginsAsync.err
    [webapp]/[webpack]/lib/Compiler.js:510:14
  
  - Tapable.js:202 next
    [webapp]/[tapable]/lib/Tapable.js:202:11
  
  - CachePlugin.js:78 Compiler.<anonymous>
    [webapp]/[webpack]/lib/CachePlugin.js:78:5
  
  - Tapable.js:204 next
    [webapp]/[tapable]/lib/Tapable.js:204:14
  
  - index.js:2018 
    [webapp]/[hard-source-webpack-plugin]/index.js:2018:7

**Comment by jivinivan** [comment]
I'm seeing this as well.

**Comment by MonikaMahanthappa** [comment]
I'm getting this error as well on 0.5.14 with rails 5

**Comment by abogaart** [comment]
This might be related to #240 as **sourcesContent** is a property of **sourceMap.map** which can be **undefined**.

**Comment by mzgoddard** [comment]
@abogaart's #240 change is released in `0.5.15`. Let me know if that fixes it for y'all. If any of you can report your devtool or SourceMapDevToolPlugin settings and any loaders on the breaking module that'd help me try to figure out a regression test for this.

You can find out the module by adding a console.log before the breaking line of code.

```js
console.log(cacheItem.resource);
```

**Comment by MrFrankel** [comment]
Still happening on 0.5.15.
source maps set to - cheap-eval-source-map;

All loaders tunnel thorough happypack:
ts-loader
script-loader
raw-loader
less-loader
css-loader
pug-loader

Sample of the error (original is much longer)



ERROR in ./node_modules/ob-daterangepicker/dist/styles/ob-daterangepicker.css
Module build failed: ChunkRenderError: Cannot read property 'sourcesContent' of undefined
    at Compilation.createChunkAssets (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/webpack/lib/Compilation.js:1416:22)
    at sealPart2 (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/webpack/lib/Compilation.js:655:10)
    at Compilation.applyPluginsAsyncSeries (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/tapable/lib/Tapable.js:195:46)
    at Compilation.seal (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/webpack/lib/Compilation.js:605:8)
    at applyPluginsParallel.err (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/webpack/lib/Compiler.js:504:17)
    at /Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ./node_modules/ob-daterangepicker/dist/styles/ob-daterangepicker.css
 @ ./static/modules/site/vendor.ts

ERROR in   Error: Child compilation failed:
  Cannot read property 'sourcesContent' of undefined:
  TypeError: Cannot read property 'sourcesContent' of undefined
  
  - compiler.js:76 
    [webapp]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:300 compile
    [webapp]/[webpack]/lib/Compiler.js:300:11
  
  - Compiler.js:510 applyPluginsAsync.err
    [webapp]/[webpack]/lib/Compiler.js:510:14
  
  - Tapable.js:202 next
    [webapp]/[tapable]/lib/Tapable.js:202:11
  
  - CachePlugin.js:78 Compiler.<anonymous>
    [webapp]/[webpack]/lib/CachePlugin.js:78:5
  
  - Tapable.js:204 next
    [webapp]/[tapable]/lib/Tapable.js:204:14
  
  - index.js:2018 
    [webapp]/[hard-source-webpack-plugin]/index.js:2018:7
  
  


ERROR in   Error: Child compilation failed:
  Cannot read property 'sourcesContent' of undefined:
  TypeError: Cannot read property 'sourcesContent' of undefined
  
  - compiler.js:76 
    [webapp]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:300 compile
    [webapp]/[webpack]/lib/Compiler.js:300:11
  
  - Compiler.js:510 applyPluginsAsync.err
    [webapp]/[webpack]/lib/Compiler.js:510:14
  
  - Tapable.js:202 next
    [webapp]/[tapable]/lib/Tapable.js:202:11
  
  - CachePlugin.js:78 Compiler.<anonymous>
    [webapp]/[webpack]/lib/CachePlugin.js:78:5
  
  - Tapable.js:204 next
    [webapp]/[tapable]/lib/Tapable.js:204:14
  
  - index.js:2018 
    [webapp]/[hard-source-webpack-plugin]/index.js:2018:7
  
  


ERROR in   Error: Child compilation failed:
  Cannot read property 'sourcesContent' of undefined:
  TypeError: Cannot read property 'sourcesContent' of undefined
  
  - compiler.js:76 
    [webapp]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:300 compile
    [webapp]/[webpack]/lib/Compiler.js:300:11
  
  - Compiler.js:510 applyPluginsAsync.err
    [webapp]/[webpack]/lib/Compiler.js:510:14
  
  - Tapable.js:202 next
    [webapp]/[tapable]/lib/Tapable.js:202:11
  
  - CachePlugin.js:78 Compiler.<anonymous>
    [webapp]/[webpack]/lib/CachePlugin.js:78:5
  
  - Tapable.js:204 next
    [webapp]/[tapable]/lib/Tapable.js:204:14
  
  - index.js:2018 
    [webapp]/[hard-source-webpack-plugin]/index.js:2018:7
  
  


ERROR in chunk vendor [initial]
site/[name].js
Cannot read property 'sourcesContent' of undefined

ERROR in chunk app [initial]
site/[name].js
Cannot read property 'sourcesContent' of undefined
webpack: Failed to compile.

**Comment by MrFrankel** [comment]
works with #source-map, though extremely slow

**Comment by MrFrankel** [comment]
also works with eval, seems cheap-eval-source-map is the instigator

**Comment by mzgoddard** [comment]
@MrFrankel Awesome. Yeah, I was able to immediately reproduce with cheap-eval-source-map. So #240 doesn't fix that case then. I'll look deeper into this soon, if someone doesn't fix it before me.

**Comment by MrFrankel** [comment]
@mzgoddard Great! thanks for addressing this, and all the work on the plugin, very useful!
For now ill move to eval until a fix it out.
