### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by simonbw** [mzgoddard/hard-source-webpack-plugin#242]
This plugin had been working fine for me, then I ran into this error when trying to start my app.

```
SyntaxError: Unexpected end of JSON input

  - hard-source-append-serializer.js:407 Readable.<anonymous>
    [project-root]/[hard-source-webpack-plugin]/lib/hard-source-append-serializer.js:407:43

  - hard-source-append-serializer.js:212
    [project-root]/[hard-source-webpack-plugin]/lib/hard-source-append-serializer.js:212:13
```

I deleted `node_modules/.cache/hard-source` and everything worked again.

I have been unable to reproduce this error. If it comes back, I will investigate further and post more information.

**Comment by mzgoddard** [comment]
`0.7` is moving to a new serializer that rewrote append to be more maintainable, less error prone, and accidentally faster. Find more information here: https://github.com/mzgoddard/hard-source-webpack-plugin/issues/297#issuecomment-389136896
