### ISSUE TITLE
Is there a quiet / silenced mode?

### ISSUE THREAD

**Issue by felipenmoura** [mzgoddard/hard-source-webpack-plugin#247]
It always logs into my terminal the message that is is creating a new `confighash path`.
Can I simply hide it?
If not, perhaps a adding an option for that might be a good feature :)

**Comment by mzgoddard** [comment]
@felipenmoura You can use this little plugin to silence the logging.

```js
function SilentHardSource() {}
SilentHardSource.prototype.apply = function(compiler) {
  compiler.plugin('hard-source-log', function(message) {
    if (message.level !== 'error' && message.level !== 'warning') {
      console[message.level].call(
        console,
        'hard-source:' + message.from, message.message
      );
    }
  });
}
```

There is some documentation on this here: https://github.com/mzgoddard/hard-source-webpack-plugin/blob/master/lib/logger-factory.js#L1-L33

Gonna use this issue to remind myself to raise the documentation to the README and add an option to HardSource that'll map to a tiny plugin like this.

**Comment by felipenmoura** [comment]
Thanks, that worked.
I just had to invert the `!==` for `===` and `&&` for `||`.

**Comment by l5x** [comment]
This would be nice as an option ;-)

**Comment by mzgoddard** [comment]
I've added an option `info` which currently takes an object with `mode` and `level` options. Setting `mode` to `'test'` will set `level` to `'warn'`, only emitting `'warn'` and `'error'` level messages. More common messages have been given lower levels.

I'll add a `'level'` for full silence soon.
