### ISSUE TITLE
EPERM: operation not permitted, rename

### ISSUE THREAD

**Issue by JonWallsten** [mzgoddard/hard-source-webpack-plugin#260]
After updating to from 0.5.15 -> 0.5.16 i can no longer build a bundle.
Always stops at 94% with the following error:

EPERM: operation not permitted, rename 'C:\Users\*\repo\web-lib\.tmp\HDCache\module\table.json.637953978' -> '
C:\Users\*\repo\web-lib\.tmp\HDCache\module\table.json'

Windows 10
Node @ 8.9.4
Webpack @ 3.10.0
Hard Source Webpack Plugin @ 0.5.16

Edit: The issue seems to be connected to the upgrading of node rather then the update to 0.5.16. I did them both in a short time span. However 8.9.4 is the new LTS for node, so I guess it should work. I'm happy to help investigating. Let me know!

Edit 2: When debugging with nodes --inspect it seems to work. Race condition?

Edit: 3 Did some more digging. The file is already named "table.json" without the suffix numbers, so I guess it makes sense that it can't rename it.

**Comment by mzgoddard** [comment]
Oh tricky. The table file is being written atomically. It writes to a temporary location, deletes the old copy, and renames the new one to that spot. This is great in case the write fails if the cache already existed, the cache will still be useful in your next build cause it has the old table. Some entries are out of date and will be rebuilt again, but that's better than the cache becoming corrupted.

Node and Windows have a long history with lib `fs` operations, emitting EPERM and ENOENT if related disk operations happen too close together.

I'll add a retry mechanic to the cache writing code and make the failure soft if it happens after the tries so webpack can finish.

Thanks for the details @JonWallsten.

**Comment by JonWallsten** [comment]
Perfect! Thank you!

**Comment by mischkl** [comment]
Unforunately this problem is still cropping up regularly for us on Windows. :cry:

**Comment by JonWallsten** [comment]
@mischkl I've added another PR that should resolve the issue. Just waiting for @mzgoddard to approve it.
