### ISSUE TITLE
Are there any plans to support Webpack 4?

### ISSUE THREAD

**Issue by rosenfeld** [mzgoddard/hard-source-webpack-plugin#261]
It seems Webpack 4 is bringing some great improvements. HardSourceWebpackPlugin helped reducing the build time a lot for our project, so I'll probably wait for it to support webpack 4 before upgrading webpack. Could you please let us know once Webpack 4 support is added?

**Comment by mzgoddard** [comment]
@rosenfeld already done! Its in the the alpha releases of v0.6 for hard-source-webpack-plugin.

https://twitter.com/zofgames/status/957651216162525184

I'm aiming to release 0.6 as stable around wepback 4's release candidate or for its first non-prerelease version. 0.6 is stable right now, passes all the current tests (some plugin tests are skipped, have to wait for them to release webpack 4 versions). I'm doing a lot of big changes right now to speed up hard-source and better take advantage of changes in webpack 4. So I might break it while in alpha.

It'd be great if you could give it a run with any projects you're testing with webpack 4, and let me know if you find any bugs.

**Comment by rosenfeld** [comment]
Oh, that's awesome! Currently I'm missing webpack 4 support for the ManifestPlugin before I can give it a try. I also use some plugins that are not still compatible with webpack 4 such as HtmlWebpackPlugin, but the ManifestPlugin is really required because we use it to serve the JS links in the server-generated index page. I've subscribed to the webpack 4 related issues for the ManifestPlugin, so I should be notified once it's done and then I'll be able to give it a try. I'll have to disable the usage of the CommonsChunkPlugin and figure out later how to properly setup the initial vendors chunk in webpack 4, but it should allow me to test the HardSource plugin meanwhile. I'll upgrade to the latest version of HardSource plugin anyway and will report any issues I find. Thanks!
