### ISSUE TITLE
Is babel-loader a required dependency?

### ISSUE THREAD

**Issue by eu81273** [mzgoddard/hard-source-webpack-plugin#264]
I recently found that babel-loader v7.x.x was added as a dependency on package.json.

hard-source-webpack-plugin supports webpack v1 through v3, but babel-loader v7.x.x only supports webpack v3.

Is really hard-source-webpack-plugin required babel-loader v7.x.x?

**Comment by mzgoddard** [comment]
It's a dev dependency. It was in the package.json "dependencies" section until the other day or so. Update your hard-source-webpack-plugin dependency.

https://github.com/mzgoddard/hard-source-webpack-plugin/blob/086056095ade6b62386f5fb9c3a7bd42b996398f/package.json#L30-L33
