### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by JonWallsten** [mzgoddard/hard-source-webpack-plugin#265]
Sorry to bother you again with this. But it seems like there are still unresolved issues concerning this rename bug.

Error: EPERM: operation not permitted, rename 'C:\Users\me\repo\web-app\\.tmp\HDCache\module~' -> 'C:\Users\me\repo\web-app\\.tmp\HDCache\module'

I don't understand how do. It's clear the rimraf should have deleted the destination folder in before copying. And I guess the promise should not be resolved until that is done? I know rimraf on windows is slow, but it shouldn't report back that the folder is removed if it isn't, right?

I did some testing:
```
.then(function() {
    console.log('------------- RIMRAF -----------');
    console.log('Path: ', _this.path);
    console.log('------------- /RIMRAF -----------');
    return rimraf(_this.path);
})
.then(timeout100)
.then(function() {
    if (fs.existsSync(_this.path)) {
        console.log('------------- FILE EXISTS -----------');
        console.log('Path: ', _this.path);
        console.log('------------- /FILE EXISTS -----------');
    }
    return rename(copy.path, _this.path);
});
```
Output: 

```
------------- RIMRAF -----------
Path:  C:\Users\me\repo\web-app\.tmp\HDCache\a23434e38d0ea5f1410985676cac446b6bac023e3bb90fe64f660177fddef85b\module
------------- /RIMRAF -----------
Error: EPERM: operation not permitted, rename 'C:\Users\me\repo\web-app\.tmp\HDCache\a23434e38d0ea5f1410985676cac446b6bac023e3bb90fe64f660177fddef85b\module~' -> 'C:\Users\me\repo\web-app\.tmp\HDCache\a23434e38d0ea5f1410985676cac446b6bac023e3bb90fe64f660177fddef85b\module'
```

So it's not because rimraf fails. The source path seems to be read-only at that moment.

**Comment by mzgoddard** [comment]
Closing based on old merged PR.
