### ISSUE TITLE
"Error: Could not find file ..."

### ISSUE THREAD

**Issue by syuilo** [mzgoddard/hard-source-webpack-plugin#272]
Thanks for this great plugin! ❤️ 

When using Vue with TypeScript, I encountered a "Could not find file" error when I reedit a file.
Of course, this bug does not appear when without hard-source-webpack-plugin.

**Here's a minimum reproducible repo: https://github.com/syuilo/hard-source-webpack-plugin-bug**

## Steps to reproduce:
1. `npm run build`
2. edit *message.ts* as you like.
   * e.g. `Hi` to `Hello`
3. `npm run build` --> Error

Once this bug appears, it will not be able to build normally until you delete the cache (`./node_modules/.cache`).

---
Version: I tried `0.5.18` and `0.6.0-alpha.8`.

Sorry my bad English! Thanks in advance.

**Comment by mzgoddard** [comment]
@syuilo Use ts-loader's happyPackMode option

```js
{
  loader: 'ts-loader',
  options: {
    happyPackMode: true,
    appendTsSuffixTo: [/\.vue$/]
  }
}
```

I don't know ts-loader well but I'm guessing in the default behaviour its building a new copy of message.js but not a new version of app.vue. But ts-loader looks for an up to date version of app.vue?

I can confirm from you reproduction repo that app.vue is in the cache and all good. Just something miss-firing around typescript output versions?
