### ISSUE TITLE
webpack4 unsupported

### ISSUE THREAD

**Issue by holdfuture** [mzgoddard/hard-source-webpack-plugin#303]
webpack4 unsupported

**Comment by NN---** [comment]
I use with Webpack 4.6.0 and see no problem.

**Comment by bzbetty** [comment]
Hadn't used this plugin before, tried to add to project.

"webpack": "4.6.0",
"offline-plugin": "^4.9.1",
"hard-source-webpack-plugin": "^0.6.4",

had 'Cannot read property 'map' of undefined' error, moved HardSourceWebpackPlugin to be last plugin and it built.

Built again and got

> TypeError: Cannot read property 'split' of undefined
    at C:\git\OurPower.Site\client\node_modules\hard-source-webpack-plugin\index.js:922:22
    at Array.forEach (<anonymous>)
    at C:\git\OurPower.Site\client\node_modules\hard-source-webpack-plugin\index.js:914:31
    at Array.forEach (<anonymous>)
    at C:\git\OurPower.Site\client\node_modules\hard-source-webpack-plugin\index.js:886:39
    at <anonymous>

>    // Loaders specified in a dependency are searched for from the
>             // context of the module containing that dependency.
>             var loaderMissing = missingCache.loader[JSON.stringify([
>               resolveKey[1],
>               loader.split('?')[0]
>             ])];

removed OfflinePlugin, it could rebuild reliably.

updated OfflinePlugin to 5.0.0 (released today) - still didn't work together.

**Comment by williamoliveira** [comment]
@bzbetty your issue is the same as #289.
offline-plugin author said he will be taking a look on his side

**Comment by NekR** [comment]
https://github.com/mzgoddard/hard-source-webpack-plugin/issues/289#issuecomment-385174857

**Comment by christiannguyen** [comment]
Any updates on this? I'm on webpack 4 and not using the offline plugin or anything. I get cannot read replace of undefined after the first build.

**Comment by xXValhallaCoderXx** [comment]
I agree, there seems to be an issue recently, 
I am on Webpack v4.8.1 and am also getting `Cannot read property 'replace' of undefined` after my first build of my project

**Comment by dsabanin** [comment]
Seems to be related to parsing JSON files after first run.

**Comment by mzgoddard** [comment]
Open separate issues. Saying webpack 4 is unsupported isn't actionable information.

If the issue is with OfflinePlugin open an issue with that. Or with whatever error you are getting.
