### ISSUE TITLE
doesn't rebuild dynamic chunks unless the cache changes

### ISSUE THREAD

**Issue by faceyspacey** [mzgoddard/hard-source-webpack-plugin#306]
So if you delete your `dist` dir, and build your app, dynamic chunks won't be in the resulting bundle. This isn't in reference to *rebuilds*, but just regular builds, *whenever the config hash* hasn't changed.

**webpack version: 4.5**

**splitChunks config:**
```js
splitChunks: {
      cacheGroups: {
        vendor: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendor',
          chunks: "all"
        },
        lang: {
          test: /[\\/]i18n[\\/]/,
          chunks: 'async'
        }
      }
    }
```

I saw this issue and subsequent PR:
https://github.com/mzgoddard/hard-source-webpack-plugin/issues/176
https://github.com/mzgoddard/hard-source-webpack-plugin/pull/215

But in my case, the dynamic imports aren't nested. I simply have one in my entire app:

```js
import(/* webpackChunkName: "lang/[request]" */'../i18n/' + lang) 
```

I also tested without using a dynamic expression, and still have the same issue:

```js
import('../i18n/en') 
```
It must be a webpack 4 issue. Also note: the issue occurs without using any `config.optimizations` options.

Also note: this isn't just a stats issue. The actual dynamic import chunks are not in fact built, nor on re-builds when watching with `webpack-dev-server`.

**Comment by faceyspacey** [comment]
Ok, this is happening with basically zero customizations of the webpack config. ..I'm gonna make you a repro? do you have an example repo you'd like me to re-use?

**Comment by phuongnd08** [comment]
Happening with our project as well. Is there a possible workaround for this?

**Comment by leggomuhgreggo** [comment]
Call me "American singer-songwriter Pink" because I'm trying to _get this_ (rebuilding dynamic chunks) _party started_.

**Comment by leggomuhgreggo** [comment]
@faceyspacey did you ever find a go-to reduced test case to fork for bug illustration purposes?

**Comment by faceyspacey** [comment]
I made the PR with a failing test:

https://github.com/mzgoddard/hard-source-webpack-plugin/pull/308

This is actually a duplicate of https://github.com/mzgoddard/hard-source-webpack-plugin/issues/300

so I'm closing.
