### ISSUE TITLE
Doesn't work with html-webpack-plugin

### ISSUE THREAD

**Issue by panrafal** [mzgoddard/hard-source-webpack-plugin#31]
On the second run, compilation fails with following error (stack shortened for brevity):

```
[Compilation]
  Error: /app/guide/guide.html.ejs:519
  /******/  modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
                             ^
  TypeError: Cannot read property 'call' of undefined

  - guide.html.ejs:519 __webpack_require__
    /app/guide/guide.html.ejs:519:30

  - index.js:225 HtmlWebpackPlugin.evaluateCompilationResult
    [html-webpack-plugin]/index.js:225:26
```

It does not depend on the html template used. It fails even if template is empty.

From what I've gathered, html-webpack-plugin does a "child compilation" and evaluates it's result.

@ampedandwired, can you shed some light on this?

**Comment by mzgoddard** [comment]
@panrafal HardSource works with the html plugin. There may be some combination of options to the html plugin and webpack that isn't working.

This error is one that pops up when a cached module depends on another module but the Dependency that represents that isn't cached. That leads to subsequent builds omitting that needed module. Can you post the original line that is causing the error and the transformed?

I can't remember if html plugin has an option to output the compiled template. You should be able to get it with a plugin like:

```js
    {
      apply: function(compiler) {
        compiler.plugin('compilation', function(compilation) {
          if (/html-webpack-plugin/.test(compilation.compiler.name)) {
            compilation.plugin('after-optimize-assets', function() {
              Object.keys(compilation.assets).forEach(function(key) {
                require('fs').writeFile(require('path').join('debug-html-assets', key), compilation.assets[key].source());
              });
            });
          }
        });
      },
    }
```

**Comment by panrafal** [comment]
@mzgoddard  The template I'm testing with is just a "Html content goes here". The compiled template contains the webpack runtime, my template stub and lodash (I'm using default template parser).

The line in the compiled template that's the root cause is this:
```
      /* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(12)(module), (function() { return this; }())))
```

It's the last line of the lodash module, and it require's module id 12, while the template contains only 0, 1 & 2

**Comment by panrafal** [comment]
Interesting thing is that on first compilation, this line looks like this:

```
       	/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(2)(module), (function() { return this; }())))
```

The module 2 is the webpack polyfill:

```
  /* 2 */
  /***/ function(module, exports) {

    module.exports = function(module) {
      if(!module.webpackPolyfill) {
        module.deprecate = function() {};
        module.paths = [];
        // module.parent = undefined by default
        module.children = [];
        module.webpackPolyfill = 1;
      }
      return module;
    }
```

On the second build, using cache, the same line requires module ID 12. The webpack polyfill is under id 12 in the chunk.

If I use a custom loader for the template (like `raw!template.html`), the lodash is not being required and the whole thing works

**Comment by panrafal** [comment]
After some more checks, it seems that if the template requires a module that is also being used by the application, it'll request these modules by ids from the app, not from the compiled template.

Hope it helps. It may be something with our setup, as it's pretty complex. If you can't reproduce it, I'll try to strip it down...
Btw, it's webpack 1.x

**Comment by mzgoddard** [comment]
Oh man this. I had this happen once and after deleting the cache it just fixed itself. I'm not sure what it is yet. Maybe it isn't exactly what I experienced before though. I ran into it testing some hot module stuff and the module id it pointed to in a second build had a second id added.

Your issue isn't the id becoming 12. Its two ids where there should be one. Though if it is doing that why is it appending a different id. If it is that issue and its getting a different id it'd seem its two issues interacting together.

That the id can change is really weird. The whole point HardSource tries to approach is to make the module unable to change and if it needs to lets webpack do a fresh build of that individual module. Makes me wonder if the module did a normal build and something else is going thats still really weird.

I'm going to look to reproduce. If you can strip down and find a smaller reproduction that would be great.

**Comment by panrafal** [comment]
If I understand the html-webpack well, it compiles the template in a "sub compilation": https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L211

I've tried to recreate it in a config, but to no avail. I even had my big config actually work once. After resetting the cache it's the same again. 

I'd say it does work by coincidence or there is some race condition going on.

Our failing config is huge & private, co I cannot share it, but maybe you have some pointers were to look at?

**Comment by texel** [comment]
Just ran into this too. I also have a big complex config that I can't share but I'll try to see if I can find a reduced test case.

**Comment by panrafal** [comment]
@mzgoddard looks like it works! thanks!
