### ISSUE TITLE
Webpack crashes: Cannot read property 'flagUsed' of undefined

### ISSUE THREAD

**Issue by 7iomka** [mzgoddard/hard-source-webpack-plugin#313]
When the assembly is restarted (when the cache is already present)
http://s1.micp.ru/PD0HL.jpg

**Comment by 7iomka** [comment]
By the tests it was found that the error causes such an import:
import 'selectize/dist/js/standalone/selectize';
How does this relate to your plugin? Without it everything works fine)

**Comment by mzgoddard** [comment]
The LocalModuleDependency is used in webpack's AMD support. The LocalModuleDependency comes up when a AMD module depends on another in the same module.

Looks like the serialization for LocalModuleDependency was missing handling to serialize and deserialize the LocalModule.
