### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by jodriscoll** [mzgoddard/hard-source-webpack-plugin#316]
```bash
｢wdm｣: TypeError: Cannot read property 'map' of undefined
    at /{path}/{project}/node_modules/hard-source-webpack-plugin/index.js:659:12
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

"`hard-source-webpack-plugin`": "`0.6.4`"
"`node`": "`v8.9.4`"
"`npm`": "`5.6.0`"

Running within a React (Slingshot) project. Apparently some users are able to prop the same app up without issue, whereas I'm not. Any ideas?

**Comment by jodriscoll** [comment]
**Update:**
When executing `yarn install` I'm presented with the error reported. However, if I run `npm i` within the same app, the error is ignored.

The author may want to revisit the error handling? I'm not entirely sure why I'm presented with two different experiences between `npm` and `yarn`, but boy, was that a silly blocker.

**Comment by sebinsua** [comment]
This sounds like this [webpack 4 is unsupported](https://github.com/mzgoddard/hard-source-webpack-plugin/issues/303) issue.

**Comment by 7iomka** [comment]
Cannot read property 'map' of undefined
This error appear on 3.x latest webpack version, in my case, after I installed prepack-webpack-plugin
http://s2.micp.ru/jfHek.jpg
See please..

**Comment by mzgoddard** [comment]
@sebinsua Saying `This sounds like this webpack 4 is unsupported issue.` does not help me fix this. That linked issue does not contain actionable information for me to fix. Instead people have responded with separate distinct issues. This issue #316 is actionable. It specifies a specific error and importantly a stack trace.

**Comment by mzgoddard** [comment]
@jodriscoll what other webpack plugins are you using?

**Comment by sebinsua** [comment]
Sorry, I didn't mean to anger you. The issue I linked to seems to have been used for people to drop in a mix of unrelated issues, but [the first error message I saw](https://github.com/mzgoddard/hard-source-webpack-plugin/issues/303#issuecomment-379030117) looks like it occured on exactly [the same line (659)](https://github.com/mzgoddard/hard-source-webpack-plugin/blob/master/index.js#L659).

**Comment by mzgoddard** [comment]
@sebinsua `Sorry, I didn't mean to anger you.` I wrote that sharper than I intended. Sorry. I'm frustrated I didn't prune that issue earlier so other feedback would helpfully better organize.

You are right about that first error message looks to be the same.

**Comment by dpatty** [comment]
I'm also running into this issue. Using node 8.10.0 npm 5.6.0, webpack 3.11.0. This doesn't happen to a colleague on the same project

**Comment by mzgoddard** [comment]
@dpatty That is wild you are getting it while your coworker isn't. I figured this was a race condition issue, just not sure exactly how. But anyways I'm working on a PR #319 to start `0.7-alpha` versions of hard-source that for this issue, gets rid of dataCache all together.

**Comment by rowanoulton** [comment]
We upgraded from 0.4.9 to 0.6.7 this week and are now seeing this as well:

```
TypeError: Cannot read property 'map' of undefined
    at /mnt/deploy/webapp/checkout/node_modules/hard-source-webpack-plugin/index.js:659:12
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

We're using the following plugins:

- ExtractTextPlugin
- DefinePlugin
- CommonsChunkPlugin
- UglifyJSPlugin
- ManifestPlugin
- ContextReplacementPlugin
- A home-baked localization plugin that reads an AST from the webpack parser

@mzgoddard Let me know if there's any more detail I can provide.

**Comment by mzgoddard** [comment]
Thanks @rowanoulton for this added info. I'm curious to know if the 0.7.0-alpha.X series (or installed with `hard-source-webpack-plugin@next` tag) works. The 0.7 version is focusing on improving internal systems with few new features. One of those changed systems directly affects this issue. It merges in the mechanism that is having an issue with the other system that directly depend on it.

I'm not sure if I'll fix the issue in 0.6 a second time with the change in 0.7.

**Comment by mzgoddard** [comment]
Finally encountered this myself on a project using `0.6`. It looks like this will happen if a project has child compilers and any one of the child compilers completes without the parent compiler. A "cache" is there but its incomplete and returns some cache data. In the case of this specific bug, relating to dataCache, the dataCache is written after the root (parent of all parent) compilers finishes. So when hard-source tries to load the full cache dataCache comes back empty and the code goes on ahead assuming its a full instead of incomplete cache.

I'm not immediately sure how to solve signaling that a prior cache is not complete. I'm more hopeful of what I can think of to be more portable (implementable in 0.6 without high time cost) than 0.7's solution. Any solution will also add to 0.7's robustness.

**Comment by srekanui** [comment]
This is FIXED after installing "hard-source-webpack-plugin": "0.7.4"
Thanks

**Comment by SeanFelipe** [comment]
upgrading to `0.7.6` fixed the issue for me. Thanks @srekanui !
