### ISSUE TITLE
Cannot read property '_hardSourceResetCache' of undefined

### ISSUE THREAD

**Issue by andreventuravale** [mzgoddard/hard-source-webpack-plugin#320]
My program started looping into this issue recently:

Cannot read property '_hardSourceResetCache' of undefined
    at Object.exports.call (.../node_modules/hard-source-webpack-plugin/lib/util/plugin-compat.js:154:48)
    at Promise.all.then.stamps (.../node_modules/hard-source-webpack-plugin/index.js:369:24)
    at <anonymous>

===

Default options used at plugin instance creation

"hard-source-webpack-plugin": "0.7.0-alpha.0"
"webpack": "3.12.0"

**Comment by andreventuravale** [comment]
At moment of that call tapable.__hardSource_hooks is undefined.

**Comment by nodatall** [comment]
I am having the same problem

**Comment by mzgoddard** [comment]
@andreventuravale Do you get that error if you run `webpack` without `--watch` (also don't run as `webpack-dev-server`)?

My guess is looking at that code a webpack `Watcher` instance is being passed instead of a `Compiler` instance.

**Comment by andreventuravale** [comment]
@mzgoddard, you might be right, we run the server in watch mode.
Can I provide you any more context?

**Comment by mzgoddard** [comment]
@andreventuravale If you can run it with the `webpack` cli script (or with grunt/gulp/insert larger build pipeline here) without `--watch` two times, and the second works. That should give me the context I need. You can also try running with https://github.com/mzgoddard/hard-source-webpack-plugin/pull/323. Which should fix the issue.

**Comment by andreventuravale** [comment]
Hey @mzgoddard, due to the complexity and customization of our building tool here I am afraid I can't reproduce the testing scenarios you asked me for.

I would say that if one of the folks here could run those that would be great. Otherwise I would say you can close this defect due to lack of context.

@nodatall, do you think you can run those testing scenarios?

**Comment by andreventuravale** [comment]
Btw, I tested with latest version and it didn't work for me either, another issue started happening and this time I could no have any stack trace.

Feel free to close this defect if you see fits.

**Comment by mzgoddard** [comment]
@andreventuravale I have a pretty good feeling #323 should solve the original stack trace in this issue. Please do open more issues for other problems you run into.
