### ISSUE TITLE
Cached value is 'null' in CacheMd5 when @require in stylus 

### ISSUE THREAD

**Issue by piecyk** [mzgoddard/hard-source-webpack-plugin#330]
### Expected Behavior

> Should not throw an exception

### Actual Behavior

> Throws an exception

#### Is an error being thrown?

```
✖ ｢wdm｣: TypeError: Cannot read property 'hash' of null
    at Object.keys.forEach.key (/Users/piecyk/work/web/node_modules/hard-source-webpack-plugin/lib/CacheMd5.js:209:48)
    at Array.forEach (<anonymous>)
    at md5CacheSerializer.read.then.then._md5Cache (/Users/piecyk/work/web/node_modules/hard-source-webpack-plugin/lib/CacheMd5.js:204:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Steps to Reproduce

Basic when changing styles in some `Gloabl.styl` that looks like 
```stylus
@require 'lib/css/fonts'
html
  margin 0
```
Hard source will throw with the exception above, when change `margin` 
for example to 10px on `next run`... Looks like the cached value is null

Will dig more, current when patching this with https://github.com/piecyk/hard-source-webpack-plugin/commit/f6268f164934c721b4dab6beeb5931a41daa9a17
everything works as expected 

Essential package.json 
 ```
"webpack": "4.8.3",
"hard-source-webpack-plugin": "0.7.0-alpha.3",
"stylus-loader": "3.0.2",
```
webpack config stylus rule 
```
{
  test: /\.styl$/,
  use: [
    MiniCssExtractPlugin.loader,
    {loader: 'css-loader', options: cssOptions},
    {loader: 'postcss-loader', options: postcssOptions},
    {
      loader: 'stylus-loader',
      options: {
        'resolve url': true,
        paths: 'src',
        preferPathResolver: 'webpack',
        import: [path.resolve(srcPath, 'lib', 'css', 'global_mixins.styl')],
        sourceMap: false
      }
    }
  ]
},
```

**Comment by piecyk** [comment]
hmm it looks like values are set, but on next run... 
It's not removed from `unbuildMd5s` that's way ti's null 🤔

**Comment by piecyk** [comment]
Yeah 👍 it's path madness, basic here 

https://github.com/mzgoddard/hard-source-webpack-plugin/blob/37f33f7eda0da84e7baf3ed793113c4f8495bbbd/lib/CacheMd5.js#L238

key is an absolute path set to null for example 
`unbuildMd5s['/Users/piecyk/work/web/src/lib/css/fonts.styl'] = null`

but here where we want to remove the maybe to remove 
https://github.com/mzgoddard/hard-source-webpack-plugin/blob/37f33f7eda0da84e7baf3ed793113c4f8495bbbd/lib/CacheMd5.js#L401

it's `delete unbuildMd5s['src/lib/css/fonts.styl'];`

that's way it's not removed, hmm it would be good to normalize the file paths ...

Overall @mzgoddard awesome changes, much more easy to follow what is happening  👏

**Comment by piecyk** [comment]
running it like this 
```js
  new HardSourceWebpackPlugin({
    cacheDirectory: path.resolve(webpackCacheDir, 'hard-source/[confighash]'),
  }),
  new HardSourceWebpackPlugin.SerializerAppendPlugin(),
```
the same output 
```
No cached value for key = /Users/piecyk/work/web/src/lib/css/fonts.styl
```

**Comment by piecyk** [comment]
It looks like when normalize the file path between `_hardSourceWriteCache` and `_hardSourceReadCache` it works... Basic in write you use `relateNormalPath` but in read `contextNormalPath` hmm question what choose here?

**Comment by mzgoddard** [comment]
@piecyk Does #332 answer this issue?

**Comment by piecyk** [comment]
Yeah it's resolved 👍 thanks @mzgoddard
