### ISSUE TITLE
Second Build Caches Old CSS Using mini-css-extract-plugin

### ISSUE THREAD

**Issue by dtothefp** [mzgoddard/hard-source-webpack-plugin#339]
### Expected Behavior

Changing CSS when using mini-css-extract-plugin should persist changes to subsequent builds.

### Actual Behavior

Changing CSS when using mini-css-extract-plugin work with live / hot reload but upon exiting the process and starting a new build previous CSS at time of first build persists rather than updated CSS.

### Steps to Reproduce

I'm not sure of the intended use case of how CSS should update with caching but now if I save CSS and refresh the browser I will see updated CSS. But, if I quit the process and rebuild with the new CSS the styles will revert back to those at the time at the beginning of the first build.

I made a branch of my repo with updated plugin to v0.6.9 https://github.com/dtothefp/hard-cache-mini-css-webpack-4/tree/update-0.6.9

Steps to reproduce:
- `yarn install`
- `yarn start`
- go to `src/main.css` and change the background color
- refresh the browser and you will see the new CSS background color
- quit the Node process and run `yarn start` again
- open the browser and see that the CSS has reverted back to the original i.e. `blue` at the time of first build

### Operating System, Node, and NPM dependency versions

```
Mac OS 10.12.6
Node 8.11.0

  "dependencies": {
    "autoprefixer": "^7.1.2",
    "babel-loader": "^7.1.4",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-register": "^6.26.0",
    "clean-webpack-plugin": "^0.1.19",
    "css-loader": "^0.28.10",
    "hard-source-webpack-plugin": "^0.6.9",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.4.0",
    "postcss-loader": "2.1.1",
    "prop-types": "^15.6.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-hot-loader": "^4.1.1",
    "style-loader": "^0.20.3",
    "webpack": "^4.6.0",
    "webpack-cli": "^2.0.12",
    "webpack-dev-server": "^3.1.1"
  }
```

**Comment by mzgoddard** [comment]
May be related to #302.

**Comment by mzgoddard** [comment]
May be related to #316.

**Comment by dtothefp** [comment]
@mzgoddard think this fixed my issue https://github.com/mzgoddard/hard-source-webpack-plugin/pull/346

Thanks!!
