### ISSUE TITLE
Option to disable timestamp comparison

### ISSUE THREAD

**Issue by alexose** [mzgoddard/hard-source-webpack-plugin#36]
Part of how hard-source-webpack-plugin invalidates the cache is to check the timestamps of the source files.  This is all well and good on a single machine, but it prevents CI environments from being able to successfully share a build cache (barring some trickery).

Would it make more sense to store a hash of each file's contents rather than timestamps?

**Comment by mzgoddard** [comment]
Thank you @alexose for opening this issue. I want this to be possible in `0.1` but I don't want to support it in `0.0.x`. For this kind of thing I'm currently considering these kind of features by whether they support the single machine case or rather a developer on the machine they develop on. As well as I'd need to build enough of `env-hash` (the dependency doing the mentioned work) to replace it. Its not really that much but its extra surface area I don't want to do currently.

To answer your technical question, what is included in the hash is the timestamps of the directories in the given directories array, the timestamps of the package.json files in child directories, and the content of the package.json files in child directories.

Eventually for `1.0` I'm thinking `env-hash` would be an optional dependency that if installed is the default behaviour but plugin hooks would be available to overwrite that functionality either way to any degree a developer may need. An alternative to env-hash could also be chosen for a good default. (Ultimately any good "default" will hopefully be light on options.)

**Comment by alexose** [comment]
Thanks for the detailed response, @mzgoddard.  Can't argue with your logic there :)

For future developers looking for a solution, I ended up using a script (from [this[(http://stackoverflow.com/questions/1964470) discussion) to set my source's timestamps equal to git's last modified date.

This makes me slightly uneasy since I haven't done any research to know if this is a good idea.  Still, it seems to be working in our Travis environment.
