### ISSUE TITLE
Error upon incremental build in webpack-dev-server when using speed-measure-webpack-plugin (Cannot read property 'call' of undefined)

### ISSUE THREAD

**Issue by tototoben** [mzgoddard/hard-source-webpack-plugin#361]
### Expected Behavior

> Webpack incremental build changes would be successfully applied to application.

### Actual Behavior

> The plugin throws an error and bundle is not built with `webpack-dev-server` left hanging.

```
[hard-source:core] Tracking environment changes with package-lock.json.
[hard-source:core] HardSourceWebpackPlugin is reading from and writing to a confighash path: [PROJECT_PATH]/node_modules/.cache/hard-source/0f2ca21329ac9c78eb29a0e430851900a0c364d9abeb399e72cb5074046b790f
✖ ｢wdm｣: TypeError: Cannot read property 'call' of undefined
    at Object.exports.call ([PROJECT_PATH]/node_modules/hard-source-webpack-plugin/lib/util/plugin-compat.js:169:17)
    at Proxy.run ([PROJECT_PATH]/node_modules/hard-source-webpack-plugin/lib/SystemArchetype.js:184:20)
    at args ([PROJECT_PATH]/node_modules/speed-measure-webpack-plugin/WrappedPlugin/index.js:52:19)
    at _fn0.then._result0 (eval at create ([PROJECT_PATH]/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:13:1)
    at <anonymous>
```

### Steps to Reproduce

> - Wrap a webpack config that uses `hard-source-webpack-plugin` with `speed-measure-webpack-plugin`

### Operating System, Node, and NPM dependency versions

```
Fedora 27
Node 8.11.1
npm 6.1.0

"devDependencies": {
    "hard-source-webpack-plugin": "^0.7.2",
    "speed-measure-webpack-plugin": "^1.2.2",
    "webpack": "^4.10.0",
    "webpack-bundle-analyzer": "^2.12.0",
    "webpack-cli": "^2.1.4",
    "webpack-dev-server": "^3.1.4",
    "webpack-merge": "^4.1.2"
}
```

So I found out the problem (`speed-measure-webpack-plugin`, dunno how it took so long to notice it in the stack trace, d'oh) during writing this report and am content with the workaround of only using one or the other at once, but thought it might be nice to post my findings here anyway.
Thanks for this plugin, the build time improvement is very nice!

**Comment by mzgoddard** [comment]
@tototoben can you open an issue on speed-measure-webpack-plugin as well. hard-source registers a hook for it to use and that the hook is not available when it would otherwise call. Clearly as hard-source works fine without speed-measure this hook should be available for hard-source to call.

**Comment by tototoben** [comment]
Found an analogous issue in their tracker, seems the problem is in sights:
https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/21
Thanks again for your work on this plugin!

**Comment by bovas85** [comment]
just an update, seems it's not fixed yet
