### ISSUE TITLE
Problem with CacheModuleResolver

### ISSUE THREAD

**Issue by omarstreak** [mzgoddard/hard-source-webpack-plugin#362]
We have a pretty sophisticated tool chain so digging into the depths of reproduction steps are too onerous for me right now. What I can say is that [Line 140 of CacheModuleResolver](https://github.com/mzgoddard/hard-source-webpack-plugin/blob/master/lib/CacheModuleResolver.js#L140) was throwing an error. I fixed this locally by changing that line to be: 
```
const normalMissing =
                (
                  missingCache[normalId] &&
                  missingCache[normalId][
                    JSON.stringify([
                      resolveKey[1],
                      resolveItem.resource.split('?')[0],
                    ])
                  ]
                );
```

What was happening was that normalId was being set to a key that didn't exist in missingCache, and so missingCache[normalId][...] would result in trying to access a property on undefined.

Another thing I found was that pretty much every resolveItem.resolveOptions in the moduleResolveCache was set to an empty object i.e. ```{}``` however, for one of the entries the resolveItem.resolveOptions was set to an object with a couple of properties, this would result in a different normalId that wasn't on missingCache and thus the exception.

I tried to trace how the resolveItem and resolveItem.resolveOptions were generated and where those properties were coming from, etc, but got stuck. My guess is that my patch is just papering over a more fundamental issue, so if you have some feedback/advice on figuring out what's going on at a deeper level that would be helpful, thanks!

**Comment by mzgoddard** [comment]
@omarstreak I just encountered one issue that related to CacheModuleResolver. It'd be great to know if 0.7.3 with https://github.com/mzgoddard/hard-source-webpack-plugin/pull/358 by change also fixed it. I'm working on a change to incorporate your suggestion either way.
