### ISSUE TITLE
on rebuild with warm caches the static assets are missing

### ISSUE THREAD

**Issue by KnisterPeter** [mzgoddard/hard-source-webpack-plugin#378]
### Expected Behavior

Static assets should be written to disk when restarting the webpack process with an existing cache.

### Actual Behavior

Static assets (e.g. images or fonts) are missing (at least when copied with `CopyWebpackPlugin`).

#### Is an error being thrown?

No, it builds without error.

### Additional info

May be related to #357

**Comment by jamalsoueidan** [comment]
I moved to cache-loader for this specific issue with assets, didn't find a solution.

**Comment by mzgoddard** [comment]
@KnisterPeter @jamalsoueidan Are you experiencing #367? Are the assets that are not exported depended on by your css? Which plugin or loader is not exporting assets when combined with `hard-source-webpack-plugin`?

**Comment by KnisterPeter** [comment]
We just use the `file-loader` to import font files (for example). After restarting the webpack process the font files are not emitted to the output directory.
