### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by jamalsoueidan** [mzgoddard/hard-source-webpack-plugin#380]
### Expected Behavior

Creating DLL manifest file using hard source webpack plugin.

### Actual Behavior

```javascript
module.exports = {
  entry: {
    vendor: ["react", "react-dom", "redux", "react-redux"]
  },
  output: {
    filename: "[name]-manifest.dll.js",
    path: base.path.project("build"),
    library: "[name]"
  },
  plugins: [
    new HardSourceWebpackPlugin({
      cacheDirectory: base.path.project("cache", "hard-source", "[confighash]")
    }),
    new webpack.DllPlugin({
      name: "[name]",
      path: base.path.project("build/[name]-manifest.json"),
      context: base.path.project()
    })
  ]
};

```

#### Is an error being thrown?

911161@N100494 C:\Users\911161\reactjs\build-process
> npm start

> unified-build-process@2.0.9 prestart C:\Users\911161\reactjs\build-process
> webpack --mode development --config webpack/dll.js

C:\Users\911161\reactjs\build-process\node_modules\hard-source-webpack-plugin\index.js:104
  );
  ^
SyntaxError: Unexpected token )
    at NativeCompileCache._moduleCompile (C:\Users\911161\reactjs\build-process\node_modules\v8-compile-cache\v8-compile-cache.js:226:18)
    at Module._compile (C:\Users\911161\reactjs\build-process\node_modules\v8-compile-cache\v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (C:\Users\911161\reactjs\build-process\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\911161\reactjs\build-process\webpack\dll.js:5:33)
    at Module._compile (C:\Users\911161\reactjs\build-process\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)

### Steps to Reproduce

Install node 7.5,

This error is thrown because of the node version, when I upgrade to 8.x.x the error is gone.

### Operating System, Node, and NPM dependency versions

```
Windows 10
Node 7.5.0

  "dependencies": {
    "@types/react": "^16.3.16",
    "@types/react-dom": "^16.0.5",
    "cache-loader": "^1.2.2",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "file-loader": "^1.1.11",
    "fork-ts-checker-webpack-plugin": "^0.4.2",
    "fs": "0.0.1-security",
    "fs-extra": "^6.0.1",
    "happypack": "^5.0.0",
    "hard-source-webpack-plugin": "^0.7.5",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.4.0",
    "minimist": "^1.2.0",
    "node-sass": "^4.9.0",
    "postcss-loader": "^2.1.5",
    "postcss-preset-env": "^5.1.0",
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-hot-loader": "^4.2.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "request": "^2.87.0",
    "sass-loader": "^7.0.2",
    "shorthash": "0.0.2",
    "style-loader": "^0.21.0",
    "thread-loader": "^1.1.5",
    "ts-loader": "^4.3.1",
    "tslint": "^5.10.0",
    "tslint-config-prettier": "^1.13.0",
    "tslint-eslint-rules": "^5.3.1",
    "tslint-react": "^3.6.0",
    "typescript": "^2.9.1",
    "webpack": "^4.10.2",
    "webpack-cli": "^2.1.5",
    "webpack-dev-server": "^3.1.4",
    "webpack-hot-middleware": "^2.22.2",
    "webpack-merge": "^4.1.2"
  },
```

**Comment by mzgoddard** [comment]
Thank you @jamalsoueidan for taking the time to open this issue. I released version `0.7.6` around when you opened this issue, which added an engine check to clarify what was previously just in the CHANGELOG that `0.7.x` and later supports Node `>=8`.

**Comment by PierreGUI** [comment]
Hey guys, it's possible the check for node version doesn't work.
I've just had this exact same issue with my ubuntu server running node v6.11.0 & npm 6.4.1
Glad I've found this issue otherwise I would still be debugging 👍 
Cheers

**Comment by mdo5004** [comment]
I am also having this issue using node v6.14.1

**Comment by jbrill** [comment]
Any update on a workaround?
