### ISSUE TITLE
Marking files as sideEffects-free does not work when run with HardSource

### ISSUE THREAD

**Issue by niieani** [mzgoddard/hard-source-webpack-plugin#390]
### Expected Behavior

Compilation of modules marked as sideEffects-free is the same when run with HardSource, and it's not.

The `data` of each `module` inside of `normalModuleFactory` should contain the `descriptionFileData` property, which is used to mark the module as sideEffect-free:

https://github.com/webpack/webpack/blob/e3678aa3767aaeb26ebcf5e3028412bbebdb4f9f/lib/optimize/SideEffectsFlagPlugin.js#L28

### Actual Behavior

When run with HardSource, property `descriptionFileData` is undefined, this means the logic of `SideEffectsFlagPlugin` is never executed and the modules are not marked as sideEffects-free.

#### Is an error being thrown?

No. It's broken silently.

### Steps to Reproduce

1. Import a module marked as sideEffects-free
2. Run the same compilation with and without HardSource -- the output will differ

### Operating System, Node, and NPM dependency versions

HardSource 0.9.0
Webpack 4.12.0
macOS 10.13.4 (17E202)
Node 10.5.0

**Comment by mzgoddard** [comment]
I've identified the missing feature. The parent object containing `descriptionFileData` isn't being carried through the enhanced-resolve cache. So this data isn't being populated in the NormalModuleFactory and passed to SideEffectsFlagPlugin.

**Comment by mzgoddard** [comment]
Thanks @niieani for opening this issue. I knew previously that hard-source supported side effects false through the webpack config but had overlooked side effects false in the package.json. Now both should be covered.
