### ISSUE TITLE
Production mode: custom UglifyJSPlugin options or file-based devtool config not cached

### ISSUE THREAD

**Issue by rmunch** [mzgoddard/hard-source-webpack-plugin#393]
### Expected Behavior

When production mode is enabled, in either of the following cases I expect uglification and sourcemaps to be cache between builds:

* Custom UglifyJSPlugin options passed into `config.optimization.minimizers` (ex. to enable `sourceMaps: true`
* When the `devtool` setting is set to `source-map` or `hidden-source-map`

### Actual Behavior

In the two above cases, sourcemaps and uglification are not cached between builds, which causes the build to take much longer than when cached.

Note that when no `devtool` config is set to `none` or `eval` (possibly others), *and* no customization of `UglifyJSPlugin` is passed into `config.optimization.minimizers`, uglification is cached.

#### Is an error being thrown?

No.

### Steps to Reproduce

The default config in production mode will cache uglification between builds (note that in production mode, uglification is on by default, and no source maps are generated as expected since the default `devtool` setting is `none`):

```
config = {
    mode: 'production'
};
```

But in either of the following two cases, uglification and/or sourcemaps are not cached between builds:

```
config = {
    mode: 'production',
    devtool: 'source-map'
};
```

```
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
...
config = {
    mode: 'production';
    optimization: {
        minimizer: [
            new UglifyJsPlugin()
        ]
    }
};
```

### Operating System, Node, and NPM dependency versions

```
Mac OS 10.13.5
Node 10.4.1

"dependencies": {
    "clean-webpack-plugin": "^0.1.19",
    "css-loader": "^0.28.11",
    "exports-loader": "^0.7.0",
    "expose-loader": "^0.7.5",
    "file-loader": "1.1.11",
    "hard-source-webpack-plugin": "0.9.0",
    "html-webpack-plugin": "^3.2.0",
    "imports-loader": "^0.8.0",
    "inline-manifest-webpack-plugin": "^4.0.0",
    "less": "2.6.1",
    "less-loader": "4.1.0",
    "null-loader": "0.1.1",
    "raw-loader": "0.5.1",
    "style-loader": "^0.21.0",
    "svgo": "1.0.5",
    "svgo-loader": "2.1.0",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "webpack": "4.12.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^3.0.8"
    "eslint": "4.19.1",
    "eslint-loader": "2.0.0",
    "unused-files-webpack-plugin": "3.4.0",
}
```

**Comment by mzgoddard** [comment]
@rmunch thank you for opening this issue. How are you determining that the work isn't cached? hard-source currently caches modules before they are uglified. Since their uglification depends on the rest of their container chunk their uglified state cannot be cached by hard-source. Are the pre-uglified modules not being cached? A simple test would be to see if the `node_modules/.cache/hard-source` grew in size.

My understanding is this later work is cached by UglifyJsPlugin and is done at a chunk level. Rebuilt chunks due to changes in modules need to re-uglified. Maybe there are configurations that UglifyJsPlugin cannot cache.

**Comment by rmunch** [comment]
@mzgoddard everything appears to be cached up until the UglifyJsPlugin runs (and then source maps). Based on your explanation, it sounds like this issue is out of the scope of this plugin and depends on the UglifyJsPlugin's cache settings, so I'll go ahead and close this ticket.

Thank you for this great plugin!
