### ISSUE TITLE
lodash-es  tree shaking not working with HardSourceWebpackPlugin

### ISSUE THREAD

**Issue by websolutions-hamburg** [mzgoddard/hard-source-webpack-plugin#399]
### Expected Behavior

If you use `lodash-es` with e.q. this import code in TypeScript:

```
import {identity} from 'lodash-es';
```
I expect that the tree shaking functionality from webpack will work, and remove all unused lodash code.

### Actual Behavior

With HardSourceWebpackPlugin the full lodash library with all modules will be included in the `bundle.js` file. I can't use the tree shaking functionality. The only way at the moment is to use this import declaration instead:
```
import identity from 'lodash-es/identity';
```

#### Is an error being thrown?

No

### Steps to Reproduce

Described in the behavior sections.

### Operating System, Node, and NPM dependency versions

```
Win 10
Node 10.3.0
Yarn 1.7.0

"devDependencies": {
    "@types/lodash-es": "4.17.0",
    "hard-source-webpack-plugin": "0.10.1",
    "html-webpack-plugin": "3.2.0",
    "lodash-es": "4.17.10",
    "node-sass": "4.9.0",
    "postcss-loader": "2.1.5",
    "sass-loader": "7.0.3",
    "style-loader": "0.21.0",
    "ts-loader": "4.4.2",
    "typescript": "2.9.2",
    "uglifyjs-webpack-plugin": "1.2.7",
    "webpack": "4.15.0",
    "webpack-bundle-analyzer": "2.13.1",
    "webpack-cli": "3.0.8",
    "webpack-dev-server": "3.1.4"
}
```

**Comment by mzgoddard** [comment]
@websolutions-hamburg Thank you for opening this issue. The missing feature is being tracked in #390.
