### ISSUE TITLE
Time to release 0.x.0 ?

### ISSUE THREAD

**Issue by MoOx** [mzgoddard/hard-source-webpack-plugin#40]
This will allow to push patch directly without people upgrading the package all the time.
[This plugin will be added to create-react-app](https://github.com/facebookincubator/create-react-app/issues/615) so it's a big deal to be able to get patch without having to manually update the number and cut a new release (same apply for Phenomic).

Do you think it's ready for prime time?

**Comment by mzgoddard** [comment]
Yeah I think its time. The config is expressive enough and enough complexity is handled that a lot of the more recent fixes could be patches to `0.X`.

**Comment by MoOx** [comment]
Feel free to close when you will cut 0.1.0 :)

**Comment by mzgoddard** [comment]
Yeah. I wanted to get most of current Issues handled. Which is done now so here we go I guess.
