### ISSUE TITLE
Moving to version 0.7.0 and above module gives compile errors

### ISSUE THREAD

**Issue by sstewart199** [mzgoddard/hard-source-webpack-plugin#401]
### Expected Behavior

> when I run npm run I expect hard-source-webpack-plugin to work as intended.

### Actual Behavior

> When I run `npm run` with the hard-source-webpack-plugin I am getting the following error ONLY from version 0.7.0 onwards. Prior to 0.7.0 the module works great.

`/node_modules/hard-source-webpack-plugin/index.js:103
  );
  ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)`

and when I inspect  index.js I can see 

![image](https://user-images.githubusercontent.com/8428488/42412276-fc0c6d9a-8200-11e8-893d-bc7624fa3fb1.png)

notice the trailing comma.
One it is removed it moves onto another line with another trailing ,

### Operating System, Node, and NPM dependency versions

```
Mac OS 10.13.5
Node v6.10.0

"devDependencies": {
     "babel-cli": "6.26.0",
    "babel-core": "6.26.3",
    "babel-eslint": "7.2.3",
    "babel-istanbul": "0.12.2",
    "babel-jest": "21.2.0",
    "babel-loader": "7.1.4",
    "babel-plugin-add-module-exports": "0.1.4",
    "babel-plugin-react-html-attrs": "2.1.0",
    "babel-plugin-react-intl": "2.4.0",
    "babel-polyfill": "6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "6.24.1",
    "webpack": "2.7.0"
}
```

**Comment by sstewart199** [comment]
Upgraded to webpack v3.10.0 still having the same issue.

**Comment by mzgoddard** [comment]
@sstewart199 Thank you for taking the time to open this issue. However hard-source 0.7 and later only work with Node 8 and later. Node 6 and its NPM version should give you a warning or error that hard-source does not support the Node 6 engine. hard-source 0.7.6 [added the engine check](https://github.com/mzgoddard/hard-source-webpack-plugin/commit/d1f9c5fbc6717d24d89e494aaa1192b3213e15e9#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) to package.json.
