### ISSUE TITLE
Sometimes assets are not emitted

### ISSUE THREAD

**Issue by MoOx** [mzgoddard/hard-source-webpack-plugin#44]
I have a situation where some assets required via js (`require(./some-file.jpg`) and consumed via file-loader are not correctly emitted. If I disable the cache, files are emitted correctly.
I was able to reproduce 100% of the time, but since I disabled and renabled, the cache has changed and I don't have the issue anymore.

Any idea about this issue?

**Comment by MoOx** [comment]
Well in fact I can reproduce all the time.

```console
git clone https://github.com/MoOx/phenomic.git
cd phenomic
npm install && npm run docs # grab a coffee
cd docs
npm run build # first build, open dist/_ and see _ & src
npm run build # cached build, open dist/_ and see only _, src is missing
```

**Comment by mzgoddard** [comment]
I think a change in extract text for webpack 2 is causing this. Its making it not possible for hard source to track dependencies to the css and to the files emitted by file loader. I'll have to look at this further.

**Comment by MoOx** [comment]
I am actually using webpack 1.

**Comment by spalger** [comment]
@MoOx the extract-test plugin is making changes in order to support both

**Comment by mzgoddard** [comment]
@MoOx Oh yeah. I hadn't checked extract text v1 yet so I made a bad assumption. Looks like HardSource had't supported this at all yet. Looks like something I'll want to add for directly supporting ExtractText.

The use case is ExtractText running a child compiler in the loader to build the source it stores on a namespaced key. That doesn't transfer dependencies so the rebuild with HardSource doesn't recreate the file-loader modules to create those assets.

I'm going to look at specifically supporting ExtractText. I'm not sure yet if their is a general method to support this use case.

**Comment by MoOx** [comment]
@mzgoddard this issue is back for me. I recently upgraded to 0.2.x and I am facing this issue again. Exact same problem: no cache, build is ok, with cache, build skip some files that should be emitted by file-loader via the css :(

**Comment by MoOx** [comment]
Still having issues with 0.3.x. Is this related to #71?
