### ISSUE TITLE
Fails to work with terser-webpack-plugin

### ISSUE THREAD

**Issue by aldarund** [mzgoddard/hard-source-webpack-plugin#442]
### Expected Behavior

No errors

### Actual Behavior

Second build ( from cache ) of nuxt project fails

#### Is an error being thrown?

```
ERROR in b7c4800071ccd1e2b2fe.js from Terser
Unexpected token punc «{», expected punc «,» [b7c4800071ccd1e2b2fe.js:10,66]

ERROR in 76f4f3fa37d499eb8fbf.js from Terser
Unexpected token punc «{», expected punc «,» [76f4f3fa37d499eb8fbf.js:13,66]

ERROR in 9ddcbb908062ba233aea.js from Terser
Unexpected token punc «{», expected punc «,» [9ddcbb908062ba233aea.js:13,66]
...
```

### Steps to Reproduce

Nuxt switched to use of terser-webpack-plugin https://github.com/nuxt/nuxt.js/pull/3928
And this make hard source not work anymore.

### Operating System, Node, and NPM dependency versions

```
Win 10
Node 10

"dependencies": {
      "nuxt-edge": "2.0.0-25624675.b69cabe",
}
```

**Comment by benfavre** [comment]
I get this now whatever version of nuxt I use.
Can't pin point the issue ...

Any Luck ?

**Comment by aldarund** [comment]
It will happen in nuxt 2.0 + until it get fixed here

**Comment by benfavre** [comment]
It worked fine a few days ago with older versions of nuxt 2.0 so it's most likely a peer dependency of nuxt and not nuxt itself

**Comment by aldarund** [comment]
@benfavre i linked what caused this -> https://github.com/nuxt/nuxt.js/pull/3928 its a PR that got merged yesterday before 2.0 release

**Comment by benfavre** [comment]
If I pull a previous version of nuxt into my project I still get this issue, hence my comment

**Comment by aldarund** [comment]
@benfavre what previous version ? before this pr such thing wasnt happening.

**Comment by benfavre** [comment]
any
![image](https://user-images.githubusercontent.com/664679/45883292-f0fff480-bdb0-11e8-985d-f5348cdecfa7.png)

**Comment by aldarund** [comment]
How u could get error with terser if it wasnt used then ? :)

**Comment by benfavre** [comment]
I get Unexpected token punc «{»,
Does not sayt "from terser"

**Comment by benfavre** [comment]
My bad, I now manage to reproduce your error, when building. Not in dev mode tho.

**Comment by benfavre** [comment]
ERROR in a6f879b63dad670612db.js from UglifyJs
Unexpected token punc «{», expected punc «,» [a6f879b63dad670612db.js:2489,72]

....

**Comment by dreyks** [comment]
it's not terser, it's webpack 4.19.1
i've made #443 with reproducible repo

**Comment by aldarund** [comment]
@dreyks nice that you found real cause. Im closing this issue in favor of yours then
