### ISSUE TITLE
undefined property

### ISSUE THREAD

**Issue by KyleAMathews** [mzgoddard/hard-source-webpack-plugin#46]
Trying out hard-source-webpack-plugin with Gatsby and am running into this error on one of my projects. Not really sure how to further debug this but would to love help track this down. I'm using version 0.1.0.

```javascript
HardSourceWebpackPlugin is writing to a new confighash path for the first time: /Users/kylemathews/programs/blog/.intermediate-representation/cache/develop
/Users/kylemathews/programs/gatsby/node_modules/hard-source-webpack-plugin/index.js:599
          var identifier = identifierPrefix + result.request;
                                                    ^

TypeError: Cannot read property 'request' of undefined
  at /Users/kylemathews/programs/gatsby/node_modules/hard-source-webpack-plugin/index.js:599:53
  at /Users/kylemathews/programs/gatsby/node_modules/hard-source-webpack-plugin/index.js:551:22
```

**Comment by mzgoddard** [comment]
Err. Well this is going to be a good regression test. An earlier resolver error'd instead of returning a result. This line didn't expect that. 😮

**Comment by mzgoddard** [comment]
@KyleAMathews by the way thanks for opening this issue!

**Comment by KyleAMathews** [comment]
My pleasure! For the site I tested it with that it did work it dropped build times from ~30 secs to ~15 secs!! Starting the dev server is almost instantaneous now.
