### ISSUE TITLE
webpack crash with react virtualized when webpack updated to 4.20.2

### ISSUE THREAD

**Issue by eemt** [mzgoddard/hard-source-webpack-plugin#460]
I note [here](https://github.com/mzgoddard/hard-source-webpack-plugin/issues/455), that "webpack is not broken. hardsource is broken when working with webpack 4.19.1 and up."  I downgraded to webpack 4.19.0 and it does fix this issue.

I document here for the benefit of others with the same trouble and to encourage addressing the incompatibility.

### Expected Behavior

Successful build. 

### Actual Behavior

Our yarn build fails with this error: 

```ERROR in chunk main [entry]
target.js
C:\Dev\node_modules\react-virtualized\dist\es\index.js 5082c27d13800109498dfa47a5181abd
Unexpected token (193:79)
| }
|
| /* harmony default export */ var __WEBPACK_MODULE_DEFAULT_EXPORT__ = (undefine
d{
|   ge: dispatchBsearchGE,
|   gt: dispatchBsearchGT,
```

Deleting the cache ( node_modules\.cache\hard-source ) fixes the problem so the yarn build works again. 

#### Is an error being thrown?

Yes.  See the error. 

### Operating System, Node, and NPM dependency versions

```
Windows 7
node 8.12.0
yarn version: 1.10.1 (same error on yarn 1.9)

hard-source-webpack-plugin: 0.11.1
Last updated in July

webpack: 4.20.2

react-virtualized: 9.20.0
Last updated in July

react/react-dom/react-test-renderer 16.5.2

Some of webpack's brethren: 
    "webpack-cleanup-plugin": "^0.5.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-middleware": "^3.4.0",
    "webpack-hot-middleware": "^2.24.2",
```

**Comment by michaelsbradleyjr** [comment]
See #443.

**Comment by eemt** [comment]
Fixed with update.
