### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by 7iomka** [mzgoddard/hard-source-webpack-plugin#487]
### Expected Behavior
All works
> Please describe what should happen

### Actual Behavior
![image](https://user-images.githubusercontent.com/18473137/53306891-dcfe7880-38a3-11e9-9652-f4a83f1d8068.png)

**Comment by tannerlyons** [comment]
Near the bottom it says "JavaScript heap out of memory".

This plugin uses a lot of mem, plus if you have a large build it can take lots of mem.

'You can give webpack more memory with the node flag `--max_old_space_size`.

For example, my team uses this command: `> node --max-old-space-size=8192 node_modules/.bin/webpack --config config/webpack.conf.js  --env.NODE_ENV=production
`

**Comment by kadamwhite** [comment]
I'm going to close this out as it does not appear to be a bug with the library; but hope the heap adjustment change helped you!

**Comment by PLQin** [comment]
I also had this problem, it always caused me to compile failure and I had to give up the hard-source-webpack-plugin, too bad
