### ISSUE TITLE
AMD modules are not rebuilding correctly

### ISSUE THREAD

**Issue by spalger** [mzgoddard/hard-source-webpack-plugin#49]
example: https://github.com/spalger/reproduce-issues/tree/master/hard-source-webpack-plugin/amd

We have a few AMD modules in our codebase, and they don't get recreated correctly after a hard-reset. The build output includes the source, but the [module wrapper](https://github.com/spalger/reproduce-issues/blob/master/hard-source-webpack-plugin/amd/build/bundle.js#L60) does not include the `__webpack_require__` variable even though the `__WEBPACK_AMD_DEFINE_RESULT__` wrapper expects it.

(super excited to start using this btw, taking the 30-40 second build time for https://github.com/elastic/kibana to 2 seconds is going to be killer!)

**Comment by mzgoddard** [comment]
@spalger Thank you for opening this issue! This is similar to how CommonJS modules that just export behave. `__webpack_require__` appears in the output when a module has any dependencies (in the webpack sense, not in the dependencies list of `define` or using `require` in CommonJS). HardSource saves dependencies called ConstDependency to persist that as that is what CommonJS results in. So we just need to store a similar webpack object for AMD modules. Which can be AMDDefineDependency.
