### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by sarink** [mzgoddard/hard-source-webpack-plugin#518]
No update in 2 years, a lot of outstanding issues... what is the status?

**Comment by kadamwhite** [comment]
I've asked @mzgoddard to make me a repo admin so we can knock out a few of the long-outstanding pieces, @sarink , and he's given me those perms as of today. We could probably use some help though so if you're able to help test or maintain this, please let me know!

**Comment by IanVS** [comment]
I see a flurry of PR ~~merges~~ closes on May 19, and then nothing since then, and no releases.  I guess the question remains, is this project under active maintenance?
