### ISSUE TITLE
Alternative environment hash option

### ISSUE THREAD

**Issue by mattlewis92** [mzgoddard/hard-source-webpack-plugin#52]
First off, great module, this works flawlessly with my dev environment 😄 

The issue I'm having is getting it to work on our CI server, as the mtimes of the node_modules directory and package.json etc will always change, hence this plugin won't work on a CI server. Calculating the md5 hash of every file in the node_modules directory isn't feasible for performance reasons, however now that yarn exists, you can just compute a hash of the `yarn.lock` file, plus `package.json` and the webpack config file contents, which should give you a performant and accurate environment hash (providing you use yarn to install your dependencies)

There are 2 possible options I propose to handle this:
- add a `contentsHash: true` (there's probably a better name) option to the `environmentPaths` config that will calculate the md5 of each listed files contents, rather than using the mtime of each file.
- add an alternative `environmentHash` option that accepts a function that returns the environment hash. The user can then use whatever logic they prefer to calculate the environment hash.

Opening this up for discussion first before I start building a pull request for this, let me know what you'd prefer 😄

**Comment by alexose** [comment]
+1 to this.  I ran into the same [issue](https://github.com/mzgoddard/hard-source-webpack-plugin/issues/36), but solved it with a workaround.

**Comment by mattlewis92** [comment]
That's awesome, thanks so much for implementing this! 😄
