### ISSUE TITLE
Cannot read property '...\node_modules\extract-text-webpack-plugin' of null

### ISSUE THREAD

**Issue by brownish** [mzgoddard/hard-source-webpack-plugin#55]
Just found a small bug that I _think_ can be easily fixed. I noticed that I was getting weird errors relating to extract-text-webpack-plugin that would seemingly come and go at random. I figured out that some types like 

```
class Store {
    name =
    constructor(){
    }
}
```

or

```
const a = 1;
const a = 2;
```

would trip the extract-text-webpack-plugin error. Instead of letting webpack show the correct error, the app just crashes. I tracked down the error to `index.js` and found that `module.meta` was undefined, for some reason:

```
        if (module[extractTextNS] || module.meta[extractTextNS]) {
          moduleCache[identifier] = null;
          return;
        }
```

Checking for module.meta seems to fix the problem:

```
        if (module[extractTextNS] || module.meta && module.meta[extractTextNS]) {
          moduleCache[identifier] = null;
          return;
        }
```

**Comment by wmertens** [comment]
This started happening for me after upgrading to webpack v2.1-beta25 from v2.1-beta4

**Comment by brownish** [comment]
@wmertens I'm using beta25 as well. Forgot to mention that.
