### ISSUE TITLE
this.cacheItem.warnings.map is undefined

### ISSUE THREAD

**Issue by alexose** [mzgoddard/hard-source-webpack-plugin#57]
Just noticed this with 0.2.2:

```/Users/alexose/repo/node_modules/hard-source-webpack-plugin/lib/hard-module.js:185
  this.warnings = this.cacheItem.warnings.map(deserializeError(ModuleWarning, state), this);
                                         ^

TypeError: Cannot read property 'map' of undefined
    at HardModule.build (/Users/alexose/repo/node_modules/hard-source-webpack-plugin/l
ib/hard-module.js:185:42)
    at Compilation.buildModule (/Users/alexose/repo/node_modules/webpack/lib/Compilati
on.js:126:9)
    at /Users/alexose/repo/node_modules/webpack/lib/Compilation.js:309:10
    at onDoneResolving (/Users/alexose/repo/node_modules/webpack/lib/NormalModuleFactory.js:36:13)
    at /Users/alexose/repo/node_modules/hard-source-webpack-plugin/index.js:741:22
    at fromCache (/Users/alexose/repo/node_modules/hard-source-webpack-plugin/index.js
:682:18)
```

Haven't dug into it yet, but it only happens when reading from an existing cache.

**Comment by mzgoddard** [comment]
Oh weird. My first thought is this is a cache from before warnings and errors were supported. Do you know what version you bumped up from?

It could be something else too, its just weird if its a recent cache every module stores an errors and warnings array. Maybe something else is going on.

(Also thanks for the issue!)

**Comment by mzgoddard** [comment]
Ah so I noticed working on context module support that `loc` can sometimes be a string and part of the serializing on `loc` was turning the string into an object. Which isn't what we want in that case. So I think #63 should fix this either through the `loc` serialization improvement or stamping the cache with the library's version.
