### ISSUE TITLE
Strange caching-related errors

### ISSUE THREAD

**Issue by wmertens** [mzgoddard/hard-source-webpack-plugin#60]
I use hot reloading and this plugin, and every so often I get an error like this after an update:
```
Uncaught TypeError: Cannot call a class as a function
    at _classCallCheck (webpack:///./~/redux-form/es/Field.js?:12:99)
    at Field (webpack:///./~/redux-form/es/Field.js?:39:7)
```

It always happened with redux-form so far. When I trace through the problem, there is a mixup of exports. The webpack_requires are supposed to import one export, but in fact return another export of the same module. 

![image](https://cloud.githubusercontent.com/assets/54934/20489225/20e2fe56-b00a-11e6-98f1-48c5e8d5e471.png)
*Note how it passes export b, hoping for `reduxForm`, but in fact getting `Field`*

I don't change the redux-form code, so it's quite mysterious as to why it suddenly changes export.

The only way to make it go away is to clear the hard-source-webpack-plugin cache.

**Comment by mzgoddard** [comment]
@wmertens Thanks for opening this issue!

I'm going to guess this is a bug related to https://github.com/mzgoddard/hard-source-webpack-plugin/blob/d76d65df0089bc93fb3df5f00f1af9e0d11c58ed/index.js#L623-L637. That part invalidates cached modules if their used and usedExports change. What I'm guessing is happening is you have two (or more) modules depending on a common dependency changing the usedExports or that common dependency is updated. Either way the common dependency is rebuilt and the order of usedExports may be different depending on the order of the modules as part of webpack considers them to build usedExports.

The short of this is to fix this I believe I need to also invalidate any `reasons` (webpack's name for dependents) or ensure the existing indices is preserved for `usedExports`. Either of those solutions has the potential for instability so I'm going to think about it a little to make sure I don't cause infinite rebuilds or bad builds.
