### ISSUE TITLE
Hard source cache between dev mode and build mode should be removed

### ISSUE THREAD

**Issue by thangngoc89** [mzgoddard/hard-source-webpack-plugin#7]
I getting some weird result when trigger a production and and start the dev server right after that, the dev server emit some css files which is the result of ExtractTextPlugin. Should we handle this on our side ? 

More for information, see https://github.com/MoOx/phenomic/pull/646

**Comment by mzgoddard** [comment]
@thangngoc89 If your production and development configurations are different you'll need separate webpack cache directories. If you run the same configuration in two different webpack prcoesses with the same cache directory that could also cause weird race conditions. HardSource could do some kind of file system lock on the directory, that'd just help HardSource tell when situations like this happen and not really solve them for you.

**Comment by thangngoc89** [comment]
Ah. That explains the weird behaviour I'm getting. You should a note to readme about different cache for dev and prod build.

**Comment by mzgoddard** [comment]
@thangngoc89 good point.
