### ISSUE TITLE
Options to include or exclude modules

### ISSUE THREAD

**Issue by mzgoddard** [mzgoddard/hard-source-webpack-plugin#76]
Provide some option set that lets users control modules that get cached. This can help in situations like #70 where a plugin or loader does not work with hard-source temporarily because of a bug or without some kind of plugin for hard-source to help it understand that external plugin or loader.

One example of a bug-less situation could be a loader that builds in a resource from a server that without a plugin to hard-source to understand a way to check for rebuilds. This option set could provide an easier path for hard-source users to let the two collaborate.

**Comment by jaunkst** [comment]
This would be invaluable right now. Having issues with sass-loader performance, it smells like a memory leak or circular issue when caching. Haven't memory profiled this issue yet but I would love to be able to avoid the side effect.

**Comment by mzgoddard** [comment]
Implemented in #381.
