### ISSUE TITLE
Webpack breaks on cached run

### ISSUE THREAD

**Issue by wmertens** [mzgoddard/hard-source-webpack-plugin#79]
versions:
* hard-source-webpack-plugin v0.3.4
* webpack 2.2.0-rc.0 as well as 2.1.0-beta.25

When I run the project the first time, everything is fine, but on subsequent runs I get this crash until I clear the hard-source cache or disable the plugin:
```
/pathToProject/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:31
	var importedModule = this.importDependency.module;
	                                          ^

TypeError: Cannot read property 'module' of undefined
    at HardHarmonyImportSpecifierDependency.HarmonyImportSpecifierDependency.getWarnings (/pathToProject/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:31:44)
    at /pathToProject/node_modules/webpack/lib/Compilation.js:643:21
    at Array.forEach (native)
    at /pathToProject/node_modules/webpack/lib/Compilation.js:642:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (/pathToProject/node_modules/webpack/lib/Compilation.js:641:9)
    at Compilation.<anonymous> (/pathToProject/node_modules/webpack/lib/Compilation.js:507:8)
    at Array.forEach (native)
    at Compilation.finish (/pathToProject/node_modules/webpack/lib/Compilation.js:506:15)
    at /pathToProject/node_modules/webpack/lib/Compiler.js:471:16
    at /pathToProject/node_modules/tapable/lib/Tapable.js:189:11
    at Compilation.<anonymous> (/pathToProject/node_modules/webpack/lib/Compilation.js:454:10)
    at /pathToProject/node_modules/webpack/lib/Compilation.js:425:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Note that I run webpack with babel-register for the config files, not sure if that is related.

**Comment by mzgoddard** [comment]
Hey @wmertens. I'm guessing you are doing something out of order. Are you using something imported before its imported? We had another bug like this related to exporting things before they were imported.

Do you have anything like

```js
doSomething();
// ...
import {doSomething} from './some-file';
```

Just want to confirm so my regression test to go along with the fix keeps this from popping up again later.

**Comment by wmertens** [comment]
No before-import use, eslint would have told me (I just double-checked).

I do use `System.import(...).then(...)`, and there may be circular (but
finite) dependencies (not sure). Would any of those cause problems? Maybe
webpack itself?

**Comment by wmertens** [comment]
I added a `console.log(this)` and this error happens for this `this`:
```js
HardHarmonyImportSpecifierDependency {
  module: null,
  importDependency: undefined,
  importedVar: null,
  id: 'default',
  name: 'Promise',
  range: null,
  loc: 
   { start: { line: 5, column: 102 },
     end: { line: 5, column: 109 } } }
```

I changed it to log for `this.name === 'Promise'` and it turns out that the first run, it has Bluebird for Promise, and the second time, it shows the above output. So maybe something is using Promise before I polyfill it with Bluebird?

**Comment by wmertens** [comment]
All I needed to do was rename my bluebird import from `Promise` to something else and it stopped happening. Weird, because I never assigned to the Promise global, it seems that global name clashes are not appreciated?

**Comment by mzgoddard** [comment]
Oh wow. I think the `Promise` detail is exactly the issue. The good news is my `0.3.5` change in #80 works for this too. I'm guessing its a detail of the acorn parser webpack uses hoisting global names or some other similar mechanism effectively causing the specifier to appear before the import in the dependencies of that module.

I'm not worried about `System.import` being the cause. Its basically a fancy `require.ensure` dependency that doesn't have to deal with the more complex situations harmony imports and exports deal with.

Thanks for helping me figure this out @wmertens!

**Comment by wmertens** [comment]
🎉 can confirm it is fixed now!

Imports are hairy - I'm battling an issue where a Babel preset appears as an empty object unless I force-import it with `node -r lib/myBabelPreset` :-/
