### ISSUE TITLE
Reading from cache does not work with Webpack v2.2 final

### ISSUE THREAD

**Issue by swernerx** [mzgoddard/hard-source-webpack-plugin#88]
This is the error I get in advanced boilerplate right now:

```
Unhandled rejection TypeError: Class constructor RawModule cannot be invoked without 'new'
    at new HardModule (/Users/sebastian/Workspace/sebastian-software/advanced-boilerplate/node_modules/hard-source-webpack-plugin/lib/hard-module.js:18:13)
```

**Comment by swernerx** [comment]
I figure this is related to the fact that Webpack changed most source code to ES6 and is using ES6 classes right now. Hardsource should probably migrate as well to make `super()` work correctly.

**Comment by swernerx** [comment]
I started with a pull request on transform hardsource into ES6 + transpilation for testing and releasing. See my progress here: https://github.com/mzgoddard/hard-source-webpack-plugin/pull/89

**Comment by MoOx** [comment]
Facing this issue as well. Thank @swernerx for you work on it.

**Comment by mzgoddard** [comment]
I'm iterating on some fixes too.

Looking at using

```js
  Object.setPrototypeOf(this,
    Object.assign(
      new ModuleDependency(request),
      HardHarmonyImportDependency.prototype,
    )
  );
```

instead of the prior

```
  ModuleDependency.call(this, request);
```

I love switching to es6 (probably with babel output or something). But I don't want to drop webpack 1 support for a while.
