### ISSUE TITLE
usage with webpack-dev-server

### ISSUE THREAD

**Issue by davidmoshal** [mzgoddard/hard-source-webpack-plugin#93]
Interesting plugin, but doesn't seem to work with webpack-dev-server,
at least not without undocumented configuration?

**Comment by tim-mc** [comment]
@davidmoshal I've been able to get it working properly. What's the issue you're running into?

**Comment by MattSurabian** [comment]
I've definitely used hardsource and dev server together without issue in the past but was able to repro this in my [DuckHuntJS](https://github.com/MattSurabian/DuckHunt-JS/pull/26) repo.

After [adding hard source](https://github.com/MattSurabian/DuckHunt-JS/pull/26/commits/3ddb7998a8289c79e214b797cfdff18ac5751c02) I got an 

```Error: EACCES: permission denied, mkdir...``` 

from [line 498 of the hard source plugin](https://github.com/mzgoddard/hard-source-webpack-plugin/blob/master/index.js#L498) with the following deps:

```
    "webpack-dev-server": "^1.16.3",
    "webpack": "^2.2.1",
    "hard-source-webpack-plugin": "^0.3.9"
```

I was able to fix this issue by updating to the latest version of webpack dev server that was released earlier today (`2.3.0`) and making a [small change to my webpack config](https://github.com/MattSurabian/DuckHunt-JS/pull/26/commits/bd48476e8c37c27ba298d4919508638876fb0b5d#diff-11e9f7f953edc64ba14b0cc350ae7b9d) which ensured my `output.path` property was absolute

**Comment by davidmoshal** [comment]
I'll check versions   
Am using typescript which could be a problem.

**Comment by mzgoddard** [comment]
@davidmoshal were you able to figure this out? It may be an incompatibility with typescript-loader. If you could point me to a paired down typescript-webpack setup with at least two typescript files to be built (one depending on the other file) that would really help me build a integration test to help support using hard-source with typescript.

**Comment by davidmoshal** [comment]
OK, will try it out again

**Comment by davidmoshal** [comment]
wow, works great, speeds up compilation from 10-20 seconds down to less than 1 second!
- webpack 2.2.1
- typescrit 2.2.1
- vue 1.0.28

however, there is a problem with WallabyJS - I'll file that separately.

**Comment by mzgoddard** [comment]
Reviewing the comments this issue sounds fixed. I'm using hard-source regularly with webpack-dev-server as well. To anyone reading this issue, if webpack-dev-server and not webpack alone is having an issue, see if you can dig a little more into what about webpack-dev-server isn't working for you. Does it work and with or without HMR? Are you using a loader or plugin you don't use with a just webpack build? Any information you can add for a future ticket will really help narrow down the issue. A general issue with webpack-dev-server won't be enough info to create a fix.
