### ISSUE TITLE
Some modules resolve as `undefined` if old `.cache` is present

### ISSUE THREAD

**Issue by legomushroom** [mzgoddard/hard-source-webpack-plugin#94]
If the old `.cache/[config hash]/` folder is present - some modules resolve to `undefined` so build breaks. I assume that something is off with restoring modules from the cache files.

#### Environment:

- Mac OSX El Capitan
- Node@v7.2.1
- npm@3.10.10
- hard-source-webpack-plugin@0.3.9
- webpack@2.2.1

#### Plugin's config:

```js
// ...
new HardSourcePlugin({
    cacheDirectory: path.normalize(`/.cache/[confighash]/`),
    recordsPath: path.normalize(`${dirname}.cache/[confighash]/records.json`),
    configHash: function (webpackConfig) {
        const hash = require('node-object-hash')().hash(webpackConfig);
        return hash;
    },
    environmentHash: {
        root: process.cwd(),
        directories: ['node_modules'],
        files: ['package.json']
    }
})  
// ...
```

I understand that this is probably not enough info to track down this issue, so will be happy to provide more upon your request.

**Comment by mzgoddard** [comment]
What other plugins/loaders are you using? And can you share their configuration? Most issues with hard-source so far are are plugins I haven't yet tested against yet that need a minor change in hard-source to support. `0.3.9` for example was a minor change to support `webpack.IgnorePlugin`.

**Comment by mzgoddard** [comment]
Closing since this never got more info on the issue to nail down the problem.
